version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app

  dashboard:
    build: ./caseworker-dashboard
    ports:
      - '3001:3001'
    volumes:
      - ./caseworker-dashboard:/app

  mobile:
    build: ./app
    ports:
      - '19000:19000'
    volumes:
      - ./app:/app
