param(
    [string]$Output="C:\Users\SAFES\SafeStepsApp\curriculum\lessons",
    [int]$Count=5
)

Write-Host "=== SafeSteps Auto-Generate Engine ===" -ForegroundColor Cyan

for($i=1;$i -le $Count;$i++){
    $id="auto-lesson-$i"
    $obj=[PSCustomObject]@{
        id=$id
        type="lesson"
        title="Auto Lesson $i"
        content="This is autogenerated placeholder content."
    }
    $obj|ConvertTo-Json -Depth 20|Set-Content -Encoding UTF8 -Path (Join-Path $Output "$id.json")
}

Write-Host "Auto-generated $Count lessons." -ForegroundColor Green
