import React, { useCallback, useEffect, useState } from "react";
import { RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { safeStepsApiRequest } from "../../lib/safeStepsApi";

type Check={id:string;area:string;status:"pass"|"fail"|"pending";evidence_reference?:string|null};
type Gate={releaseVersion:string;decision:"go"|"no_go";blockers:string[];checks:Check[];signoffs:{signoff_role:string;review_domain:string;reviewer_name:string;review_scope:string;decision:string;condition_text?:string|null;condition_due_at?:string|null}[];releasePackage?:{status:string;change_summary:string}|null;requiredAreas:string[];};
export default function PersonalAiLaunchReadinessScreen(){
  const [gate,setGate]=useState<Gate|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);try{setError("");setGate(await safeStepsApiRequest<Gate>("/api/admin/launch-readiness/1.0.0"));}catch(cause){setError(cause instanceof Error?cause.message:"Could not load the launch gate.");}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
  const byArea=new Map(gate?.checks.map(item=>[item.area,item])??[]);
  return <ScrollView contentContainerStyle={s.container} refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>}><Text style={s.kicker}>Release 1.0.0</Text><Text style={s.title}>Launch readiness</Text><View style={[s.decision,gate?.decision==="go"?s.go:s.noGo]}><Text style={s.decisionText}>{gate?.decision==="go"?"GO":"NO-GO"}</Text></View><Text style={s.body}>SafeSteps remains NO-GO until every required evidence check passes, all specialist approvals exist, and no Sev 1 incident remains unresolved.</Text>{error?<Text style={s.error}>{error}</Text>:null}
    {gate?.blockers.length?<View style={s.blockers}><Text style={s.cardTitle}>Release blockers</Text>{gate.blockers.map(item=><Text key={item} style={s.blocker}>• {item}</Text>)}</View>:null}
    <View style={s.row}><View style={s.flex}><Text style={s.cardTitle}>Versioned review package</Text><Text style={s.meta}>{gate?.releasePackage?.change_summary||"No review package recorded"}</Text></View><Text style={[s.status,gate?.releasePackage?.status==="approved"||gate?.releasePackage?.status==="released"?s.pass:s.pending]}>{gate?.releasePackage?.status||"missing"}</Text></View>
    {gate?.signoffs.map(item=><View key={`${item.signoff_role}-${item.reviewer_name}`} style={s.row}><View style={s.flex}><Text style={s.cardTitle}>{item.signoff_role.replaceAll("_"," ")}</Text><Text style={s.meta}>{item.reviewer_name} · {item.review_domain}</Text><Text style={s.meta}>{item.review_scope}</Text>{item.condition_text?<Text style={s.blocker}>Condition: {item.condition_text}{item.condition_due_at?` · due ${new Date(item.condition_due_at).toLocaleDateString()}`:""}</Text>:null}</View><Text style={[s.status,item.decision==="approved"?s.pass:item.decision==="rejected"?s.fail:s.pending]}>{item.decision}</Text></View>)}
    {gate?.requiredAreas.map(area=>{const check=byArea.get(area);const status=check?.status??"pending";return <View key={area} style={s.row}><View style={s.flex}><Text style={s.cardTitle}>{area}</Text><Text style={s.meta}>{check?.evidence_reference||"No evidence recorded"}</Text></View><Text style={[s.status,status==="pass"?s.pass:status==="fail"?s.fail:s.pending]}>{status}</Text></View>;})}
  </ScrollView>;
}
const s=StyleSheet.create({container:{padding:20,gap:13,backgroundColor:"#eef2ef"},kicker:{fontSize:13,fontWeight:"700",textTransform:"uppercase"},title:{fontSize:29,fontWeight:"800"},body:{fontSize:15,lineHeight:22},error:{color:"#9f2d25"},decision:{padding:18,borderRadius:16,alignItems:"center"},go:{backgroundColor:"#287643"},noGo:{backgroundColor:"#9f2d25"},decisionText:{color:"white",fontSize:25,fontWeight:"900"},blockers:{backgroundColor:"#fff1ed",padding:15,borderRadius:15,gap:5},blocker:{color:"#7e2f27",lineHeight:20},row:{backgroundColor:"white",padding:14,borderRadius:14,flexDirection:"row",gap:10,alignItems:"center",borderWidth:1,borderColor:"#d8e0da"},flex:{flex:1},cardTitle:{fontWeight:"800",fontSize:16},meta:{color:"#59685f",fontSize:13,marginTop:3},status:{paddingHorizontal:9,paddingVertical:5,borderRadius:999,overflow:"hidden",fontWeight:"800"},pass:{backgroundColor:"#cdebd5",color:"#205c31"},fail:{backgroundColor:"#f3cbc7",color:"#842d26"},pending:{backgroundColor:"#eee2c6",color:"#6b5720"}});
