import React, { useCallback, useEffect, useState } from "react";
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { safeStepsApiRequest } from "../../lib/safeStepsApi";

type Referral={id:string;name:string;stealth_label:string;category:string;jurisdiction:string;status:string;phone?:string;website?:string;crisis_only:boolean;safe_for_monitored_device:boolean;last_verified_at?:string;next_review_at?:string;requires_two_person_approval:boolean;verified_by_user_id?:string;second_approved_by_user_id?:string};
export default function PersonalAiReferralsAdmin(){
  const [rows,setRows]=useState<Referral[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);try{setError("");setRows(await safeStepsApiRequest<Referral[]>("/api/admin/referrals"));}catch(cause){setError(cause instanceof Error?cause.message:"Could not load referrals.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const verify=async(id:string)=>{try{await safeStepsApiRequest(`/api/admin/referrals/${id}/verify`,{method:"POST",body:JSON.stringify({result:"verified",checks:{phone:true,website:true,hours:true,jurisdiction:true,crisisClaims:true,monitoredDeviceLabel:true},notes:"Verified in staff directory review."})});await load();}catch(cause){setError(cause instanceof Error?cause.message:"Verification failed.");}};
  return <ScrollView contentContainerStyle={s.container} refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>}><Text style={s.kicker}>Restricted staff tool</Text><Text style={s.title}>Referral verification</Text><Text style={s.body}>Only active, current entries can appear to users. Crisis and high-risk entries require independent approval. Verify against an official source before using the action below.</Text>{error?<Text style={s.error}>{error}</Text>:null}{rows.map(row=>{const overdue=!!row.next_review_at&&new Date(row.next_review_at)<new Date();return <View key={row.id} style={s.card}><View style={s.line}><Text style={s.cardTitle}>{row.name}</Text><Text style={[s.badge,overdue&&s.danger]}>{overdue?"OVERDUE":row.status.toUpperCase()}</Text></View><Text style={s.meta}>{row.category} · {row.jurisdiction}</Text><Text style={s.meta}>Visible label: {row.stealth_label||"Support option"} · Monitored-device safe: {row.safe_for_monitored_device?"Yes":"No"}</Text><Text style={s.meta}>Last verified: {row.last_verified_at?new Date(row.last_verified_at).toLocaleDateString():"Never"} · Next: {row.next_review_at?new Date(row.next_review_at).toLocaleDateString():"Not set"}</Text>{row.requires_two_person_approval?<Text style={s.warning}>Independent approval: {row.second_approved_by_user_id?"complete":"required"}</Text>:null}<View style={s.preview}><Text style={s.previewTitle}>Safe-mode preview</Text><Text>{row.stealth_label||"Support option"}</Text><Text>{row.phone?"Call available":"No call option"}{row.website&&row.safe_for_monitored_device?" · Open available":""}</Text></View><Pressable accessibilityRole="button" accessibilityLabel={`Record completed verification for ${row.name}`} style={s.button} onPress={()=>void verify(row.id)}><Text style={s.buttonText}>Record completed verification</Text></Pressable></View>})}</ScrollView>;
}
const s=StyleSheet.create({container:{padding:20,gap:14,backgroundColor:"#eef5ef"},kicker:{fontSize:13,fontWeight:"700",textTransform:"uppercase"},title:{fontSize:29,fontWeight:"800"},body:{fontSize:15,lineHeight:22},error:{color:"#922b23"},card:{backgroundColor:"white",padding:15,borderRadius:16,borderWidth:1,borderColor:"#d4dfd7",gap:7},line:{flexDirection:"row",gap:10,justifyContent:"space-between"},cardTitle:{fontSize:17,fontWeight:"800",flex:1},badge:{fontSize:12,fontWeight:"800",backgroundColor:"#dae8dd",padding:6,borderRadius:8,overflow:"hidden"},danger:{backgroundColor:"#f3cbc7",color:"#812b24"},meta:{color:"#4f6258"},warning:{color:"#765a13",fontWeight:"700"},preview:{backgroundColor:"#f5f6f5",padding:12,borderRadius:12,gap:4},previewTitle:{fontWeight:"800"},button:{backgroundColor:"#244f3d",padding:13,borderRadius:11,alignItems:"center",minHeight:48,justifyContent:"center"},buttonText:{color:"white",fontWeight:"800"}});
