import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { deletePersonalAiMoodTrends, getPersonalAiMoodTrends, type PersonalAiMoodObservation } from "../lib/safeStepsApi";

export default function PersonalAiMoodTrendsScreen(){
  const [rows,setRows]=useState<PersonalAiMoodObservation[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);try{setError("");setRows(await getPersonalAiMoodTrends());}catch(cause){setError(cause instanceof Error?cause.message:"Could not load saved mood cues.");}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
  const counts=useMemo(()=>rows.reduce<Record<string,number>>((all,row)=>({...all,[row.dominant_emotion]:(all[row.dominant_emotion]??0)+1}),{}),[rows]);
  const remove=async()=>{try{setLoading(true);await deletePersonalAiMoodTrends();setRows([]);}catch(cause){setError(cause instanceof Error?cause.message:"Could not delete saved mood cues.");}finally{setLoading(false);}};
  return <ScrollView contentContainerStyle={s.container} refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>}><Text style={s.kicker}>Optional private pattern</Text><Text style={s.title}>My communication cues</Text><Text style={s.notice}>These automated scores help SafeSteps adjust wording. They are not diagnoses, clinical measurements, evidence of progress or deterioration, or assessments of parenting capacity. Message text is not stored in these records.</Text>{error?<Text accessibilityLiveRegion="polite" style={s.error}>{error}</Text>:null}<View style={s.summary}>{["anxiety","sadness","anger","joy","neutral"].map(label=><View key={label} style={s.pill}><Text style={s.pillLabel}>{label}</Text><Text style={s.pillCount}>{counts[label]??0}</Text></View>)}</View>{rows.slice().reverse().map(row=><View key={row.id} style={s.card}><Text style={s.cardTitle}>{row.dominant_emotion}</Text><Text style={s.meta}>{new Date(row.created_at).toLocaleString()} · cue confidence {Math.round(row.confidence_score*100)}%</Text><Text style={s.meta}>Automatically expires {new Date(row.expires_at).toLocaleDateString()}</Text></View>)}{!loading&&!rows.length?<Text style={s.empty}>No opt-in mood cues are saved.</Text>:null}<Pressable accessibilityRole="button" onPress={()=>void remove()} disabled={!rows.length||loading} style={[s.delete,!rows.length&&s.disabled]}><Text style={s.deleteText}>Delete all cues and revoke consent</Text></Pressable></ScrollView>;
}
const s=StyleSheet.create({container:{padding:20,paddingBottom:40,gap:14,backgroundColor:"#f7f4ed"},kicker:{fontSize:13,fontWeight:"800",textTransform:"uppercase",color:"#286451"},title:{fontSize:29,fontWeight:"900",color:"#19372e"},notice:{fontSize:14,lineHeight:21,backgroundColor:"white",padding:15,borderRadius:14,borderWidth:1,borderColor:"#d4dfd8"},error:{color:"#8c2c24"},summary:{flexDirection:"row",flexWrap:"wrap",gap:8},pill:{flexDirection:"row",gap:7,alignItems:"center",paddingHorizontal:11,paddingVertical:8,borderRadius:999,backgroundColor:"#deeee7"},pillLabel:{textTransform:"capitalize",fontWeight:"700"},pillCount:{fontWeight:"900"},card:{backgroundColor:"white",padding:14,borderRadius:13,borderWidth:1,borderColor:"#d4dfd8",gap:4},cardTitle:{textTransform:"capitalize",fontSize:17,fontWeight:"900"},meta:{color:"#59675f",fontSize:13},empty:{padding:16,textAlign:"center",color:"#59675f"},delete:{minHeight:48,justifyContent:"center",alignItems:"center",padding:13,borderRadius:11,backgroundColor:"#872d26"},disabled:{opacity:.4},deleteText:{color:"white",fontWeight:"900"}});
