import * as Linking from "expo-linking";
import { router } from "expo-router";
import React, { useCallback, useEffect, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { safeStepsApiRequest } from "../lib/safeStepsApi";

type Mode="normal"|"safe"|"monitored_device"|"crisis";
type Referral={id:string;name:string;category:string;description?:string;phone?:string;website?:string;hours?:string;after_hours:boolean;crisis_only:boolean;safe_for_monitored_device:boolean;verified:boolean;last_verified_at?:string};
const modeCopy:Record<Mode,string>={normal:"Here are verified support options.",safe:"Only the most important details are shown.",monitored_device:"Use a safer device if someone may be watching.",crisis:"If there is immediate danger, get help now."};

export default function ReferralSupportScreen(){
  const [mode,setMode]=useState<Mode>("safe");const [rows,setRows]=useState<Referral[]>([]);const [hidden,setHidden]=useState(false);const [error,setError]=useState("");
  const load=useCallback(async()=>{try{setError("");setRows(await safeStepsApiRequest<Referral[]>(`/api/referrals?mode=${mode}&jurisdiction=AU_QLD`));}catch{setRows([]);setError("I can’t safely verify support options right now. If this is an emergency, call 000 now.");}},[mode]);
  useEffect(()=>{void load();},[load]);
  const quickExit=()=>{setRows([]);setHidden(true);router.replace("/dashboard");};
  const call=(phone?:string)=>{if(phone)void Linking.openURL(`tel:${phone.replace(/[^+\d]/g,"")}`);};
  return <ScrollView contentContainerStyle={s.container}><View style={s.header}><Text style={s.title}>Support options</Text><Pressable accessibilityRole="button" accessibilityLabel="Quick exit and hide support options" onPress={quickExit} style={s.exit}><Text style={s.exitText}>Quick exit</Text></Pressable></View>
    <View style={s.controls}><Pressable style={s.control} onPress={()=>router.push("/resources/safety-planning")}><Text style={s.controlText}>Safer device</Text></Pressable><Pressable style={s.control} onPress={()=>setHidden(value=>!value)}><Text style={s.controlText}>{hidden?"Show":"Hide"}</Text></Pressable><Pressable style={s.control} onPress={()=>setMode(mode==="normal"?"safe":"normal")}><Text style={s.controlText}>{mode==="normal"?"Use safe labels":"Visible labels"}</Text></Pressable></View>
    <Text style={s.notice}>{modeCopy[mode]}</Text>
    <View style={s.modeRow}><Pressable style={s.chip} onPress={()=>setMode("safe")}><Text>Safe</Text></Pressable><Pressable style={s.chip} onPress={()=>setMode("monitored_device")}><Text>Someone may be watching</Text></Pressable><Pressable style={s.chip} onPress={()=>setMode("crisis")}><Text>Urgent</Text></Pressable></View>
    <Pressable accessibilityRole="button" accessibilityLabel="Call emergency services on Triple Zero" style={s.emergency} onPress={()=>call("000")}><Text style={s.emergencyText}>Immediate danger? Get help now</Text></Pressable>
    {!hidden?rows.map((item,index)=><View key={item.id} style={s.card}><View style={s.cardTop}><Text style={s.cardTitle}>{mode==="normal"?item.name:`Support option ${index+1}`}</Text><Text style={s.verified}>Verified</Text></View>{item.description&&mode!=="monitored_device"?<Text style={s.body}>{item.description}</Text>:null}{item.after_hours?<Text style={s.meta}>Available after hours</Text>:null}<View style={s.actions}>{item.phone?<Pressable style={s.call} onPress={()=>call(item.phone)}><Text style={s.callText}>Call</Text></Pressable>:null}{item.website&&mode!=="monitored_device"?<Pressable style={s.open} onPress={()=>void Linking.openURL(item.website!)}><Text style={s.openText}>Open</Text></Pressable>:null}</View></View>):null}
    {!hidden&&!rows.length?<Text style={s.fallback}>{error||"No verified support options are available. Call 000 for immediate danger."}</Text>:null}<Text style={s.footer}>Referral information can change. Verify details when it is safe.</Text>
  </ScrollView>;
}
const s=StyleSheet.create({container:{padding:18,paddingBottom:40,gap:13,backgroundColor:"#fff"},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:10},title:{fontSize:28,fontWeight:"900",color:"#17211d"},exit:{backgroundColor:"#252a27",paddingHorizontal:14,paddingVertical:11,borderRadius:10},exitText:{color:"white",fontWeight:"800"},controls:{flexDirection:"row",flexWrap:"wrap",gap:8},control:{backgroundColor:"#e8eeea",padding:10,borderRadius:10},controlText:{fontWeight:"700"},notice:{backgroundColor:"#f0f4f1",padding:14,borderRadius:12,fontSize:15,lineHeight:21},modeRow:{flexDirection:"row",flexWrap:"wrap",gap:8},chip:{borderWidth:1,borderColor:"#9eaaa3",padding:9,borderRadius:999},emergency:{backgroundColor:"#a52f27",padding:15,borderRadius:12,alignItems:"center"},emergencyText:{color:"white",fontWeight:"900",fontSize:16},card:{borderWidth:1,borderColor:"#d8dfda",borderRadius:14,padding:14,gap:8},cardTop:{flexDirection:"row",justifyContent:"space-between",gap:10},cardTitle:{fontSize:17,fontWeight:"900",flex:1},verified:{color:"#25613b",fontWeight:"800",backgroundColor:"#dceee2",paddingHorizontal:8,paddingVertical:4,borderRadius:999,overflow:"hidden"},body:{fontSize:14,lineHeight:20,color:"#4e5c54"},meta:{fontSize:13,color:"#5c685f"},actions:{flexDirection:"row",gap:9},call:{backgroundColor:"#28533f",paddingHorizontal:18,paddingVertical:11,borderRadius:10},callText:{color:"white",fontWeight:"900"},open:{backgroundColor:"#e8eeea",paddingHorizontal:18,paddingVertical:11,borderRadius:10},openText:{fontWeight:"800"},fallback:{backgroundColor:"#fff0ec",padding:14,borderRadius:12,color:"#812f27",lineHeight:21},footer:{fontSize:12,color:"#667169",textAlign:"center",marginTop:6}});
