import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  screen: {
    flexGrow: 1,
    padding: 20,
    gap: 14,
    backgroundColor: "#F7FAFC",
  },
  container: {
    flex: 1,
    padding: 20,
    gap: 14,
    backgroundColor: "#F7FAFC",
  },
  title: {
    fontSize: 30,
    fontWeight: "bold",
    color: "#102033",
  },
  courseBackground: {
    flex: 1,
    backgroundColor: "#F8FCFC",
  },
  courseScreen: {
    flexGrow: 1,
    paddingTop: 118,
    paddingHorizontal: 26,
    paddingBottom: 34,
    gap: 22,
  },
  courseHeader: {
    gap: 10,
    maxWidth: 720,
  },
  courseEyebrow: {
    color: "#42A99D",
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: 0,
  },
  courseRule: {
    width: 54,
    height: 4,
    borderRadius: 8,
    backgroundColor: "#62BEB5",
  },
  courseTitle: {
    color: "#00636D",
    fontSize: 42,
    lineHeight: 48,
    fontWeight: "800",
  },
  courseSubtitle: {
    color: "#1F2933",
    fontSize: 20,
    lineHeight: 30,
    maxWidth: 650,
  },
  courseInfoRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    maxWidth: 720,
  },
  courseFeatureCard: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 22,
    maxWidth: 760,
    borderRadius: 8,
    padding: 22,
    backgroundColor: "rgba(239, 248, 248, 0.88)",
    borderWidth: 1,
    borderColor: "rgba(177, 218, 217, 0.7)",
  },
  courseFeatureIcon: {
    width: 92,
    height: 92,
    borderRadius: 46,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#DDEFEF",
  },
  courseFeatureIconText: {
    color: "#42A99D",
    fontSize: 38,
    fontWeight: "800",
  },
  courseFeatureCopy: {
    flex: 1,
    minWidth: 220,
    gap: 6,
  },
  courseSectionTitle: {
    color: "#00636D",
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "800",
  },
  courseBody: {
    color: "#1F2933",
    fontSize: 16,
    lineHeight: 24,
  },
  courseBlock: {
    maxWidth: 760,
    gap: 12,
  },
  courseBlockTitle: {
    color: "#2C9D92",
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0,
  },
  courseGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  coursePointCard: {
    flexGrow: 1,
    flexBasis: 260,
    borderRadius: 8,
    padding: 16,
    gap: 7,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderWidth: 1,
    borderColor: "#D9EAEA",
  },
  courseStepRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    minHeight: 64,
    borderTopWidth: 1,
    borderTopColor: "#D8EAEA",
    paddingVertical: 12,
  },
  courseStepNumber: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2C9D92",
  },
  courseStepNumberText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "800",
  },
  courseStepText: {
    flex: 1,
    color: "#1F2933",
    fontSize: 17,
    lineHeight: 24,
    fontWeight: "600",
  },
  coursePrompt: {
    color: "#465466",
    fontSize: 15,
    lineHeight: 22,
    fontStyle: "italic",
  },
  courseCheckIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E1F3F1",
  },
  courseCheckIconText: {
    color: "#2C9D92",
    fontSize: 18,
    fontWeight: "800",
  },
  courseXIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E8EEF0",
  },
  courseXIconText: {
    color: "#1F2933",
    fontSize: 18,
    fontWeight: "800",
  },
  courseSpeechCard: {
    flexGrow: 1,
    flexBasis: 220,
    borderRadius: 8,
    padding: 16,
    gap: 8,
    backgroundColor: "rgba(255, 255, 255, 0.92)",
  },
  courseReflectionCard: {
    maxWidth: 760,
    borderRadius: 8,
    padding: 18,
    gap: 10,
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    borderWidth: 1,
    borderColor: "#B9DDDA",
  },
  courseReflectionInput: {
    minHeight: 110,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#B9DDDA",
    backgroundColor: "#FFFFFF",
    padding: 12,
    color: "#102033",
    fontSize: 16,
    lineHeight: 22,
    textAlignVertical: "top",
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 22,
    color: "#465466",
  },
  input: {
    borderWidth: 1,
    borderColor: "#CCD6E0",
    backgroundColor: "#FFFFFF",
    padding: 14,
    borderRadius: 8,
    fontSize: 16,
  },
  textArea: {
    minHeight: 96,
    textAlignVertical: "top",
  },
  button: {
    backgroundColor: "#1666C5",
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
  },
  buttonCompact: {
    backgroundColor: "#1666C5",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  secondaryButton: {
    backgroundColor: "#E8EEF6",
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
  },
  secondaryButtonCompact: {
    backgroundColor: "#E8EEF6",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
  },
  buttonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  secondaryButtonText: {
    color: "#102033",
    fontWeight: "bold",
    fontSize: 16,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    padding: 16,
    gap: 8,
    borderWidth: 1,
    borderColor: "#E4EAF1",
  },
  cardTitle: {
    color: "#102033",
    fontSize: 18,
    fontWeight: "700",
  },
  cardText: {
    color: "#465466",
    fontSize: 14,
    lineHeight: 20,
  },
  progressTrack: {
    height: 10,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "#E8EEF6",
  },
  progressFill: {
    height: "100%",
    borderRadius: 8,
    backgroundColor: "#1666C5",
  },
  selectableItem: {
    borderWidth: 1,
    borderColor: "#D9E2EC",
    borderRadius: 8,
    padding: 12,
    gap: 4,
    backgroundColor: "#FFFFFF",
  },
  selectableItemSelected: {
    borderWidth: 1,
    borderColor: "#1666C5",
    borderRadius: 8,
    padding: 12,
    gap: 4,
    backgroundColor: "#E8F1FD",
  },
  selectableItemTitle: {
    color: "#102033",
    fontSize: 14,
    fontWeight: "700",
  },
  selectableItemTitleSelected: {
    color: "#0B4E99",
    fontSize: 14,
    fontWeight: "700",
  },
  selectableItemText: {
    color: "#465466",
    fontSize: 13,
    lineHeight: 18,
  },
  selectableItemTextSelected: {
    color: "#173B63",
    fontSize: 13,
    lineHeight: 18,
  },
  mutedText: {
    color: "#667085",
    fontSize: 13,
    lineHeight: 19,
  },
  reportText: {
    color: "#102033",
    fontSize: 13,
    lineHeight: 20,
  },
  compactBlock: {
    gap: 3,
  },
  questionBlock: {
    gap: 8,
    paddingVertical: 8,
  },
  scoreRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
  scoreButton: {
    minWidth: 40,
    minHeight: 40,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E8EEF6",
  },
  scoreButtonSelected: {
    minWidth: 40,
    minHeight: 40,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1666C5",
  },
  scoreButtonText: {
    color: "#102033",
    fontWeight: "700",
  },
  scoreButtonTextSelected: {
    color: "#FFFFFF",
    fontWeight: "700",
  },
  link: {
    color: "#1666C5",
    fontSize: 16,
    fontWeight: "600",
    paddingVertical: 8,
  },
  textLink: {
    color: "#1666C5",
    fontWeight: "700",
  },
  inlineRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    alignItems: "center",
  },
  segmentedRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
  segment: {
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "#E8EEF6",
  },
  segmentSelected: {
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "#1666C5",
  },
  segmentText: {
    color: "#102033",
    fontWeight: "700",
  },
  segmentTextSelected: {
    color: "#FFFFFF",
    fontWeight: "700",
  },
  pill: {
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "#E8EEF6",
    color: "#102033",
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 12,
    fontWeight: "700",
  },
  pillSuccess: {
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "#DCFAE6",
    color: "#067647",
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 12,
    fontWeight: "700",
  },
  priorityHigh: {
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "#FEE4E2",
    color: "#B42318",
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 12,
    fontWeight: "700",
  },
  bottomNav: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#D9E2EC",
  },
  bottomNavItem: {
    flexGrow: 1,
    minWidth: 88,
    minHeight: 44,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E8EEF6",
    paddingHorizontal: 10,
  },
  bottomNavItemActive: {
    flexGrow: 1,
    minWidth: 88,
    minHeight: 44,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1666C5",
    paddingHorizontal: 10,
  },
  bottomNavText: {
    color: "#102033",
    fontSize: 13,
    fontWeight: "700",
  },
  bottomNavTextActive: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
  },
  error: {
    color: "#B42318",
    fontSize: 14,
    lineHeight: 20,
  },
  notice: {
    color: "#067647",
    fontSize: 14,
    lineHeight: 20,
  },
});
