-- Seed additional SafeSteps multiple-choice parenting assessment items Q021-Q076.

with instrument as (
  select id from public.assessment_instruments where slug = 'safesteps-parenting-multiple-choice-v1'
)
insert into public.assessment_domains (instrument_id, name, description, weight, display_order)
select instrument.id, domain.name, domain.description, 1::numeric, domain.display_order
from instrument
cross join (
  values
    ('emotional_attunement', 'Emotional Attunement parenting knowledge and applied judgement.', 21),
    ('routine_stability', 'Routine Stability parenting knowledge and applied judgement.', 22),
    ('communication_style', 'Communication Style parenting knowledge and applied judgement.', 23),
    ('positive_discipline', 'Positive Discipline parenting knowledge and applied judgement.', 24),
    ('autonomy_support', 'Autonomy Support parenting knowledge and applied judgement.', 25),
    ('stress_management', 'Stress Management parenting knowledge and applied judgement.', 26),
    ('conflict_resolution', 'Conflict Resolution parenting knowledge and applied judgement.', 27),
    ('expectations_realism', 'Expectations Realism parenting knowledge and applied judgement.', 28),
    ('safety_awareness', 'Safety Awareness parenting knowledge and applied judgement.', 29),
    ('attachment_security', 'Attachment Security parenting knowledge and applied judgement.', 30),
    ('feedback_quality', 'Feedback Quality parenting knowledge and applied judgement.', 31),
    ('collaboration_with_child', 'Collaboration With Child parenting knowledge and applied judgement.', 32),
    ('screen_time_management', 'Screen Time Management parenting knowledge and applied judgement.', 33),
    ('parent_child_relationship', 'Parent Child Relationship parenting knowledge and applied judgement.', 34),
    ('behaviour_guidance', 'Behaviour Guidance parenting knowledge and applied judgement.', 35),
    ('empathy_development', 'Empathy Development parenting knowledge and applied judgement.', 36),
    ('cultural_sensitivity', 'Cultural Sensitivity parenting knowledge and applied judgement.', 37),
    ('transition_support', 'Transition Support parenting knowledge and applied judgement.', 38),
    ('fairness_and_bias', 'Fairness And Bias parenting knowledge and applied judgement.', 39),
    ('motivation_support', 'Motivation Support parenting knowledge and applied judgement.', 40)
) as domain(name, description, display_order)
on conflict (instrument_id, name) do update
set
  description = excluded.description,
  weight = excluded.weight,
  display_order = excluded.display_order;

with instrument as (
  select id from public.assessment_instruments where slug = 'safesteps-parenting-multiple-choice-v1'
),
domain_lookup as (
  select d.id, d.name
  from public.assessment_domains d
  join instrument i on i.id = d.instrument_id
)
insert into public.assessment_items (
  domain_id,
  item_key,
  prompt,
  item_type,
  weight,
  max_value,
  display_order,
  is_critical
)
select domain_lookup.id, item.item_key, item.prompt, 'multiple_choice', 1::numeric, null, item.display_order, false
from domain_lookup
join (
  values
    ('emotional_attunement', 'SAFEPARENT_Q021', 'Your child expresses frustration during homework. What is the most supportive response?', 21),
    ('routine_stability', 'SAFEPARENT_Q022', 'A consistent bedtime routine helps children by:', 22),
    ('communication_style', 'SAFEPARENT_Q023', 'Which communication approach best supports cooperation?', 23),
    ('positive_discipline', 'SAFEPARENT_Q024', 'Your child spills a drink accidentally. What is the most constructive response?', 24),
    ('autonomy_support', 'SAFEPARENT_Q025', 'Your child wants to choose their own clothes. What supports autonomy?', 25),
    ('stress_management', 'SAFEPARENT_Q026', 'A parent who feels overwhelmed should first:', 26),
    ('conflict_resolution', 'SAFEPARENT_Q027', 'Two siblings argue over a game. What is the healthiest approach?', 27),
    ('expectations_realism', 'SAFEPARENT_Q028', 'Which expectation is realistic for a 10-year-old?', 28),
    ('safety_awareness', 'SAFEPARENT_Q029', 'Your child wants to help in the kitchen. What is the safest approach?', 29),
    ('attachment_security', 'SAFEPARENT_Q030', 'Secure attachment is strengthened when a parent:', 30),
    ('feedback_quality', 'SAFEPARENT_Q031', 'Effective feedback focuses on:', 31),
    ('collaboration_with_child', 'SAFEPARENT_Q032', 'Collaborative problem-solving involves:', 32),
    ('screen_time_management', 'SAFEPARENT_Q033', 'Balanced screen time includes:', 33),
    ('parent_child_relationship', 'SAFEPARENT_Q034', 'Strong parent-child relationships are built through:', 34),
    ('behaviour_guidance', 'SAFEPARENT_Q035', 'When a child breaks a rule, the most constructive step is:', 35),
    ('empathy_development', 'SAFEPARENT_Q036', 'Parents help children develop empathy by:', 36),
    ('cultural_sensitivity', 'SAFEPARENT_Q037', 'Culturally sensitive parenting assessments should:', 37),
    ('transition_support', 'SAFEPARENT_Q038', 'During major life changes, children benefit most when parents:', 38),
    ('fairness_and_bias', 'SAFEPARENT_Q039', 'To avoid bias when assessing behaviour, parents should:', 39),
    ('motivation_support', 'SAFEPARENT_Q040', 'Intrinsic motivation is strengthened when parents:', 40),
    ('emotional_attunement', 'SAFEPARENT_Q041', 'Your child is unusually quiet after school. What is the most supportive first step?', 41),
    ('routine_stability', 'SAFEPARENT_Q042', 'Stable routines help children by:', 42),
    ('communication_style', 'SAFEPARENT_Q043', 'Which communication method best supports understanding?', 43),
    ('positive_discipline', 'SAFEPARENT_Q044', 'Your child breaks a toy in frustration. What is the most constructive response?', 44),
    ('autonomy_support', 'SAFEPARENT_Q045', 'Your child wants to pack their own school lunch. What supports autonomy?', 45),
    ('stress_management', 'SAFEPARENT_Q046', 'A parent feeling overwhelmed should first:', 46),
    ('conflict_resolution', 'SAFEPARENT_Q047', 'Two children argue over a shared item. What is the healthiest approach?', 47),
    ('expectations_realism', 'SAFEPARENT_Q048', 'Which expectation is realistic for a 7-year-old?', 48),
    ('safety_awareness', 'SAFEPARENT_Q049', 'Your child wants to help with gardening tools. What is the safest approach?', 49),
    ('attachment_security', 'SAFEPARENT_Q050', 'Secure attachment is strengthened when a parent:', 50),
    ('feedback_quality', 'SAFEPARENT_Q051', 'Constructive feedback focuses on:', 51),
    ('collaboration_with_child', 'SAFEPARENT_Q052', 'Collaborative decision-making involves:', 52),
    ('screen_time_management', 'SAFEPARENT_Q053', 'Balanced screen time includes:', 53),
    ('parent_child_relationship', 'SAFEPARENT_Q054', 'Strong parent-child relationships are built through:', 54),
    ('behaviour_guidance', 'SAFEPARENT_Q055', 'When a child breaks a rule, the most constructive step is:', 55),
    ('empathy_development', 'SAFEPARENT_Q056', 'Parents help children develop empathy by:', 56),
    ('cultural_sensitivity', 'SAFEPARENT_Q057', 'Culturally sensitive parenting assessments should:', 57),
    ('transition_support', 'SAFEPARENT_Q058', 'During major life changes, children benefit most when parents:', 58),
    ('fairness_and_bias', 'SAFEPARENT_Q059', 'To avoid bias when assessing behaviour, parents should:', 59),
    ('motivation_support', 'SAFEPARENT_Q060', 'Intrinsic motivation is strengthened when parents:', 60),
    ('emotional_attunement', 'SAFEPARENT_Q061', 'Your child seems overwhelmed during a busy family event. What is the most supportive response?', 61),
    ('routine_stability', 'SAFEPARENT_Q062', 'Consistent morning routines help children by:', 62),
    ('communication_style', 'SAFEPARENT_Q063', 'Which communication approach best supports cooperation?', 63),
    ('positive_discipline', 'SAFEPARENT_Q064', 'Your child refuses to clean their room. What is the most constructive response?', 64),
    ('autonomy_support', 'SAFEPARENT_Q065', 'Your child wants to choose their own after-school activity. What supports autonomy?', 65),
    ('stress_management', 'SAFEPARENT_Q066', 'A parent feeling stressed during a conflict should first:', 66),
    ('conflict_resolution', 'SAFEPARENT_Q067', 'Two siblings argue about chores. What is the healthiest approach?', 67),
    ('expectations_realism', 'SAFEPARENT_Q068', 'Which expectation is realistic for an 8-year-old?', 68),
    ('safety_awareness', 'SAFEPARENT_Q069', 'Your child wants to ride their bike near a busy street. What is the safest approach?', 69),
    ('attachment_security', 'SAFEPARENT_Q070', 'Secure attachment is strengthened when a parent:', 70),
    ('feedback_quality', 'SAFEPARENT_Q071', 'Constructive feedback should focus on:', 71),
    ('collaboration_with_child', 'SAFEPARENT_Q072', 'Collaborative problem-solving involves:', 72),
    ('screen_time_management', 'SAFEPARENT_Q073', 'Balanced screen time includes:', 73),
    ('parent_child_relationship', 'SAFEPARENT_Q074', 'Strong parent-child relationships are built through:', 74),
    ('behaviour_guidance', 'SAFEPARENT_Q075', 'When a child breaks a rule, the most constructive step is:', 75),
    ('empathy_development', 'SAFEPARENT_Q076', 'Parents help children develop empathy by:', 76)
) as item(domain_name, item_key, prompt, display_order)
  on item.domain_name = domain_lookup.name
on conflict (domain_id, item_key) do update
set
  prompt = excluded.prompt,
  item_type = excluded.item_type,
  weight = excluded.weight,
  max_value = excluded.max_value,
  display_order = excluded.display_order,
  is_critical = excluded.is_critical;

with instrument as (
  select id from public.assessment_instruments where slug = 'safesteps-parenting-multiple-choice-v1'
),
items as (
  select ai.id, ai.item_key
  from public.assessment_items ai
  join public.assessment_domains ad on ad.id = ai.domain_id
  join instrument i on i.id = ad.instrument_id
),
options as (
  select *
  from (
    values
      ('SAFEPARENT_Q021', 'A', 'Tell them to stop complaining and finish it', 0::numeric, 1),
      ('SAFEPARENT_Q021', 'B', 'Sit with them, acknowledge the frustration, and offer guidance', 1::numeric, 2),
      ('SAFEPARENT_Q021', 'C', 'Do the homework for them', 0::numeric, 3),
      ('SAFEPARENT_Q021', 'D', 'Remove the homework and let them skip it', 0::numeric, 4),
      ('SAFEPARENT_Q022', 'A', 'Reducing predictability', 0::numeric, 1),
      ('SAFEPARENT_Q022', 'B', 'Increasing confusion about expectations', 0::numeric, 2),
      ('SAFEPARENT_Q022', 'C', 'Supporting emotional regulation and sleep quality', 1::numeric, 3),
      ('SAFEPARENT_Q022', 'D', 'Making evenings more chaotic', 0::numeric, 4),
      ('SAFEPARENT_Q023', 'A', 'Giving vague instructions', 0::numeric, 1),
      ('SAFEPARENT_Q023', 'B', 'Using clear, calm, and direct language', 1::numeric, 2),
      ('SAFEPARENT_Q023', 'C', 'Using sarcasm to make your point', 0::numeric, 3),
      ('SAFEPARENT_Q023', 'D', 'Raising your voice to show urgency', 0::numeric, 4),
      ('SAFEPARENT_Q024', 'A', 'Scold them harshly', 0::numeric, 1),
      ('SAFEPARENT_Q024', 'B', 'Tell them they''re careless', 0::numeric, 2),
      ('SAFEPARENT_Q024', 'C', 'Help them clean it up and discuss being careful next time', 1::numeric, 3),
      ('SAFEPARENT_Q024', 'D', 'Ignore it completely', 0::numeric, 4),
      ('SAFEPARENT_Q025', 'A', 'Let them choose within weather-appropriate options', 1::numeric, 1),
      ('SAFEPARENT_Q025', 'B', 'Choose everything for them', 0::numeric, 2),
      ('SAFEPARENT_Q025', 'C', 'Allow only one outfit every day', 0::numeric, 3),
      ('SAFEPARENT_Q025', 'D', 'Criticise their choices', 0::numeric, 4),
      ('SAFEPARENT_Q026', 'A', 'Take steps to regulate themselves before addressing the child', 1::numeric, 1),
      ('SAFEPARENT_Q026', 'B', 'Expect the child to calm them down', 0::numeric, 2),
      ('SAFEPARENT_Q026', 'C', 'Withdraw from the child for long periods', 0::numeric, 3),
      ('SAFEPARENT_Q026', 'D', 'React impulsively', 0::numeric, 4),
      ('SAFEPARENT_Q027', 'A', 'Let them fight until they resolve it', 0::numeric, 1),
      ('SAFEPARENT_Q027', 'B', 'Choose a favourite child to keep the game', 0::numeric, 2),
      ('SAFEPARENT_Q027', 'C', 'Guide them to negotiate and take turns', 1::numeric, 3),
      ('SAFEPARENT_Q027', 'D', 'Remove the game permanently', 0::numeric, 4),
      ('SAFEPARENT_Q028', 'A', 'Managing all responsibilities without reminders', 0::numeric, 1),
      ('SAFEPARENT_Q028', 'B', 'Never showing frustration', 0::numeric, 2),
      ('SAFEPARENT_Q028', 'C', 'Following routines with occasional support', 1::numeric, 3),
      ('SAFEPARENT_Q028', 'D', 'Handling complex tasks independently', 0::numeric, 4),
      ('SAFEPARENT_Q029', 'A', 'Allow them to use sharp tools unsupervised', 0::numeric, 1),
      ('SAFEPARENT_Q029', 'B', 'Explain safety rules and supervise closely', 1::numeric, 2),
      ('SAFEPARENT_Q029', 'C', 'Ban them from the kitchen entirely', 0::numeric, 3),
      ('SAFEPARENT_Q029', 'D', 'Let them experiment freely', 0::numeric, 4),
      ('SAFEPARENT_Q030', 'A', 'Responds consistently to emotional needs', 1::numeric, 1),
      ('SAFEPARENT_Q030', 'B', 'Avoids comforting the child', 0::numeric, 2),
      ('SAFEPARENT_Q030', 'C', 'Only shows affection during achievements', 0::numeric, 3),
      ('SAFEPARENT_Q030', 'D', 'Uses emotional distance as discipline', 0::numeric, 4),
      ('SAFEPARENT_Q031', 'A', 'Criticising personality traits', 0::numeric, 1),
      ('SAFEPARENT_Q031', 'B', 'Highlighting mistakes without guidance', 0::numeric, 2),
      ('SAFEPARENT_Q031', 'C', 'Specific behaviours and improvement strategies', 1::numeric, 3),
      ('SAFEPARENT_Q031', 'D', 'Publicly pointing out errors', 0::numeric, 4),
      ('SAFEPARENT_Q032', 'A', 'Dictating solutions', 0::numeric, 1),
      ('SAFEPARENT_Q032', 'B', 'Ignoring the child''s perspective', 0::numeric, 2),
      ('SAFEPARENT_Q032', 'C', 'Working together to find a fair solution', 1::numeric, 3),
      ('SAFEPARENT_Q032', 'D', 'Letting the child decide everything', 0::numeric, 4),
      ('SAFEPARENT_Q033', 'A', 'Unlimited access', 0::numeric, 1),
      ('SAFEPARENT_Q033', 'B', 'No screens ever', 0::numeric, 2),
      ('SAFEPARENT_Q033', 'C', 'Clear limits and breaks for physical activity', 1::numeric, 3),
      ('SAFEPARENT_Q033', 'D', 'Using screens only as punishment', 0::numeric, 4),
      ('SAFEPARENT_Q034', 'A', 'Consistent warmth and communication', 1::numeric, 1),
      ('SAFEPARENT_Q034', 'B', 'Frequent criticism', 0::numeric, 2),
      ('SAFEPARENT_Q034', 'C', 'Ignoring emotional needs', 0::numeric, 3),
      ('SAFEPARENT_Q034', 'D', 'Rigid control', 0::numeric, 4),
      ('SAFEPARENT_Q035', 'A', 'Explain why the rule exists and discuss consequences', 1::numeric, 1),
      ('SAFEPARENT_Q035', 'B', 'Punish them without explanation', 0::numeric, 2),
      ('SAFEPARENT_Q035', 'C', 'Ignore the behaviour', 0::numeric, 3),
      ('SAFEPARENT_Q035', 'D', 'React with anger', 0::numeric, 4),
      ('SAFEPARENT_Q036', 'A', 'Discussing feelings and perspectives', 1::numeric, 1),
      ('SAFEPARENT_Q036', 'B', 'Avoiding emotional conversations', 0::numeric, 2),
      ('SAFEPARENT_Q036', 'C', 'Mocking emotional reactions', 0::numeric, 3),
      ('SAFEPARENT_Q036', 'D', 'Discouraging emotional expression', 0::numeric, 4),
      ('SAFEPARENT_Q037', 'A', 'Ignore cultural context', 0::numeric, 1),
      ('SAFEPARENT_Q037', 'B', 'Assume all families share identical values', 0::numeric, 2),
      ('SAFEPARENT_Q037', 'C', 'Consider cultural norms while prioritising safety', 1::numeric, 3),
      ('SAFEPARENT_Q037', 'D', 'Judge families based on stereotypes', 0::numeric, 4),
      ('SAFEPARENT_Q038', 'A', 'Avoid discussing the change', 0::numeric, 1),
      ('SAFEPARENT_Q038', 'B', 'Validate feelings and provide predictable routines', 1::numeric, 2),
      ('SAFEPARENT_Q038', 'C', 'Expect immediate adjustment', 0::numeric, 3),
      ('SAFEPARENT_Q038', 'D', 'Minimise the child''s concerns', 0::numeric, 4),
      ('SAFEPARENT_Q039', 'A', 'Rely on assumptions', 0::numeric, 1),
      ('SAFEPARENT_Q039', 'B', 'Base decisions on observable behaviour', 1::numeric, 2),
      ('SAFEPARENT_Q039', 'C', 'Favour one child consistently', 0::numeric, 3),
      ('SAFEPARENT_Q039', 'D', 'Let siblings decide consequences', 0::numeric, 4),
      ('SAFEPARENT_Q040', 'A', 'Use rewards for every task', 0::numeric, 1),
      ('SAFEPARENT_Q040', 'B', 'Encourage effort and curiosity', 1::numeric, 2),
      ('SAFEPARENT_Q040', 'C', 'Criticise mistakes harshly', 0::numeric, 3),
      ('SAFEPARENT_Q040', 'D', 'Compare the child to others', 0::numeric, 4),
      ('SAFEPARENT_Q041', 'A', 'Tell them to talk only when ready for homework', 0::numeric, 1),
      ('SAFEPARENT_Q041', 'B', 'Gently ask how they''re feeling and offer space to share', 1::numeric, 2),
      ('SAFEPARENT_Q041', 'C', 'Assume nothing is wrong and ignore it', 0::numeric, 3),
      ('SAFEPARENT_Q041', 'D', 'Tell them to stop being dramatic', 0::numeric, 4),
      ('SAFEPARENT_Q042', 'A', 'Increasing unpredictability', 0::numeric, 1),
      ('SAFEPARENT_Q042', 'B', 'Reducing emotional security', 0::numeric, 2),
      ('SAFEPARENT_Q042', 'C', 'Providing structure that supports regulation', 1::numeric, 3),
      ('SAFEPARENT_Q042', 'D', 'Making daily life more confusing', 0::numeric, 4),
      ('SAFEPARENT_Q043', 'A', 'Giving long, complex instructions', 0::numeric, 1),
      ('SAFEPARENT_Q043', 'B', 'Clear, simple, step-by-step directions', 1::numeric, 2),
      ('SAFEPARENT_Q043', 'C', 'Using sarcasm to make your point', 0::numeric, 3),
      ('SAFEPARENT_Q043', 'D', 'Speaking loudly to show authority', 0::numeric, 4),
      ('SAFEPARENT_Q044', 'A', 'Yell at them for being irresponsible', 0::numeric, 1),
      ('SAFEPARENT_Q044', 'B', 'Ignore the situation entirely', 0::numeric, 2),
      ('SAFEPARENT_Q044', 'C', 'Help them calm down and discuss better coping strategies', 1::numeric, 3),
      ('SAFEPARENT_Q044', 'D', 'Take away all their toys permanently', 0::numeric, 4),
      ('SAFEPARENT_Q045', 'A', 'Let them choose items within healthy options', 1::numeric, 1),
      ('SAFEPARENT_Q045', 'B', 'Pack everything for them', 0::numeric, 2),
      ('SAFEPARENT_Q045', 'C', 'Criticise their choices harshly', 0::numeric, 3),
      ('SAFEPARENT_Q045', 'D', 'Allow only one fixed lunch every day', 0::numeric, 4),
      ('SAFEPARENT_Q046', 'A', 'Pause and regulate themselves before responding', 1::numeric, 1),
      ('SAFEPARENT_Q046', 'B', 'Expect the child to comfort them', 0::numeric, 2),
      ('SAFEPARENT_Q046', 'C', 'React impulsively', 0::numeric, 3),
      ('SAFEPARENT_Q046', 'D', 'Withdraw from the child for long periods', 0::numeric, 4),
      ('SAFEPARENT_Q047', 'A', 'Let them fight until someone wins', 0::numeric, 1),
      ('SAFEPARENT_Q047', 'B', 'Choose a favourite child to keep it', 0::numeric, 2),
      ('SAFEPARENT_Q047', 'C', 'Guide them to negotiate and share fairly', 1::numeric, 3),
      ('SAFEPARENT_Q047', 'D', 'Remove the item permanently', 0::numeric, 4),
      ('SAFEPARENT_Q048', 'A', 'Never needing reminders', 0::numeric, 1),
      ('SAFEPARENT_Q048', 'B', 'Managing complex tasks independently', 0::numeric, 2),
      ('SAFEPARENT_Q048', 'C', 'Following routines with occasional support', 1::numeric, 3),
      ('SAFEPARENT_Q048', 'D', 'Always staying calm', 0::numeric, 4),
      ('SAFEPARENT_Q049', 'A', 'Let them use sharp tools unsupervised', 0::numeric, 1),
      ('SAFEPARENT_Q049', 'B', 'Explain safety rules and supervise closely', 1::numeric, 2),
      ('SAFEPARENT_Q049', 'C', 'Ban them from gardening entirely', 0::numeric, 3),
      ('SAFEPARENT_Q049', 'D', 'Let them experiment freely', 0::numeric, 4),
      ('SAFEPARENT_Q050', 'A', 'Responds consistently to emotional needs', 1::numeric, 1),
      ('SAFEPARENT_Q050', 'B', 'Avoids comforting the child', 0::numeric, 2),
      ('SAFEPARENT_Q050', 'C', 'Shows affection only during achievements', 0::numeric, 3),
      ('SAFEPARENT_Q050', 'D', 'Uses emotional distance as discipline', 0::numeric, 4),
      ('SAFEPARENT_Q051', 'A', 'Criticising personality traits', 0::numeric, 1),
      ('SAFEPARENT_Q051', 'B', 'Highlighting mistakes without guidance', 0::numeric, 2),
      ('SAFEPARENT_Q051', 'C', 'Specific behaviours and improvement strategies', 1::numeric, 3),
      ('SAFEPARENT_Q051', 'D', 'Publicly pointing out errors', 0::numeric, 4),
      ('SAFEPARENT_Q052', 'A', 'Dictating all choices', 0::numeric, 1),
      ('SAFEPARENT_Q052', 'B', 'Ignoring the child''s perspective', 0::numeric, 2),
      ('SAFEPARENT_Q052', 'C', 'Working together to find fair solutions', 1::numeric, 3),
      ('SAFEPARENT_Q052', 'D', 'Letting the child decide everything', 0::numeric, 4),
      ('SAFEPARENT_Q053', 'A', 'Unlimited access', 0::numeric, 1),
      ('SAFEPARENT_Q053', 'B', 'No screens ever', 0::numeric, 2),
      ('SAFEPARENT_Q053', 'C', 'Clear limits and breaks for physical activity', 1::numeric, 3),
      ('SAFEPARENT_Q053', 'D', 'Using screens only as punishment', 0::numeric, 4),
      ('SAFEPARENT_Q054', 'A', 'Consistent warmth and communication', 1::numeric, 1),
      ('SAFEPARENT_Q054', 'B', 'Frequent criticism', 0::numeric, 2),
      ('SAFEPARENT_Q054', 'C', 'Ignoring emotional needs', 0::numeric, 3),
      ('SAFEPARENT_Q054', 'D', 'Rigid control', 0::numeric, 4),
      ('SAFEPARENT_Q055', 'A', 'Explain why the rule exists and discuss consequences', 1::numeric, 1),
      ('SAFEPARENT_Q055', 'B', 'Punish them without explanation', 0::numeric, 2),
      ('SAFEPARENT_Q055', 'C', 'Ignore the behaviour', 0::numeric, 3),
      ('SAFEPARENT_Q055', 'D', 'React with anger', 0::numeric, 4),
      ('SAFEPARENT_Q056', 'A', 'Discussing feelings and perspectives', 1::numeric, 1),
      ('SAFEPARENT_Q056', 'B', 'Avoiding emotional conversations', 0::numeric, 2),
      ('SAFEPARENT_Q056', 'C', 'Mocking emotional reactions', 0::numeric, 3),
      ('SAFEPARENT_Q056', 'D', 'Discouraging emotional expression', 0::numeric, 4),
      ('SAFEPARENT_Q057', 'A', 'Ignore cultural context', 0::numeric, 1),
      ('SAFEPARENT_Q057', 'B', 'Assume all families share identical values', 0::numeric, 2),
      ('SAFEPARENT_Q057', 'C', 'Consider cultural norms while prioritising safety', 1::numeric, 3),
      ('SAFEPARENT_Q057', 'D', 'Judge families based on stereotypes', 0::numeric, 4),
      ('SAFEPARENT_Q058', 'A', 'Avoid discussing the change', 0::numeric, 1),
      ('SAFEPARENT_Q058', 'B', 'Validate feelings and provide predictable routines', 1::numeric, 2),
      ('SAFEPARENT_Q058', 'C', 'Expect immediate adjustment', 0::numeric, 3),
      ('SAFEPARENT_Q058', 'D', 'Minimise the child''s concerns', 0::numeric, 4),
      ('SAFEPARENT_Q059', 'A', 'Rely on assumptions', 0::numeric, 1),
      ('SAFEPARENT_Q059', 'B', 'Base decisions on observable behaviour', 1::numeric, 2),
      ('SAFEPARENT_Q059', 'C', 'Favour one child consistently', 0::numeric, 3),
      ('SAFEPARENT_Q059', 'D', 'Let siblings decide consequences', 0::numeric, 4),
      ('SAFEPARENT_Q060', 'A', 'Use rewards for every task', 0::numeric, 1),
      ('SAFEPARENT_Q060', 'B', 'Encourage effort and curiosity', 1::numeric, 2),
      ('SAFEPARENT_Q060', 'C', 'Criticise mistakes harshly', 0::numeric, 3),
      ('SAFEPARENT_Q060', 'D', 'Compare the child to others', 0::numeric, 4),
      ('SAFEPARENT_Q061', 'A', 'Tell them to stop being dramatic', 0::numeric, 1),
      ('SAFEPARENT_Q061', 'B', 'Ignore it and continue socialising', 0::numeric, 2),
      ('SAFEPARENT_Q061', 'C', 'Offer a quiet break and check in on their feelings', 1::numeric, 3),
      ('SAFEPARENT_Q061', 'D', 'Force them to stay and participate', 0::numeric, 4),
      ('SAFEPARENT_Q062', 'A', 'Increasing stress and confusion', 0::numeric, 1),
      ('SAFEPARENT_Q062', 'B', 'Providing predictability that reduces anxiety', 1::numeric, 2),
      ('SAFEPARENT_Q062', 'C', 'Making mornings more chaotic', 0::numeric, 3),
      ('SAFEPARENT_Q062', 'D', 'Removing all flexibility', 0::numeric, 4),
      ('SAFEPARENT_Q063', 'A', 'Clear, calm instructions with eye contact', 1::numeric, 1),
      ('SAFEPARENT_Q063', 'B', 'Long lectures about expectations', 0::numeric, 2),
      ('SAFEPARENT_Q063', 'C', 'Sarcasm to make your point', 0::numeric, 3),
      ('SAFEPARENT_Q063', 'D', 'Speaking loudly to show authority', 0::numeric, 4),
      ('SAFEPARENT_Q064', 'A', 'Yell until they comply', 0::numeric, 1),
      ('SAFEPARENT_Q064', 'B', 'Threaten severe punishment', 0::numeric, 2),
      ('SAFEPARENT_Q064', 'C', 'Break the task into smaller steps and guide them', 1::numeric, 3),
      ('SAFEPARENT_Q064', 'D', 'Clean the room for them', 0::numeric, 4),
      ('SAFEPARENT_Q065', 'A', 'Let them choose from a few realistic options', 1::numeric, 1),
      ('SAFEPARENT_Q065', 'B', 'Choose the activity for them', 0::numeric, 2),
      ('SAFEPARENT_Q065', 'C', 'Force them to pick the most challenging option', 0::numeric, 3),
      ('SAFEPARENT_Q065', 'D', 'Discourage their interest', 0::numeric, 4),
      ('SAFEPARENT_Q066', 'A', 'Pause and regulate before responding', 1::numeric, 1),
      ('SAFEPARENT_Q066', 'B', 'React immediately with frustration', 0::numeric, 2),
      ('SAFEPARENT_Q066', 'C', 'Expect the child to calm them down', 0::numeric, 3),
      ('SAFEPARENT_Q066', 'D', 'Withdraw completely', 0::numeric, 4),
      ('SAFEPARENT_Q067', 'A', 'Let them fight until someone gives up', 0::numeric, 1),
      ('SAFEPARENT_Q067', 'B', 'Assign chores based on favourites', 0::numeric, 2),
      ('SAFEPARENT_Q067', 'C', 'Guide them to negotiate a fair division', 1::numeric, 3),
      ('SAFEPARENT_Q067', 'D', 'Remove all chores permanently', 0::numeric, 4),
      ('SAFEPARENT_Q068', 'A', 'Never needing reminders', 0::numeric, 1),
      ('SAFEPARENT_Q068', 'B', 'Managing simple tasks with occasional support', 1::numeric, 2),
      ('SAFEPARENT_Q068', 'C', 'Handling complex responsibilities independently', 0::numeric, 3),
      ('SAFEPARENT_Q068', 'D', 'Always staying calm', 0::numeric, 4),
      ('SAFEPARENT_Q069', 'A', 'Allow them unsupervised', 0::numeric, 1),
      ('SAFEPARENT_Q069', 'B', 'Explain safety rules and supervise closely', 1::numeric, 2),
      ('SAFEPARENT_Q069', 'C', 'Ban bike riding entirely', 0::numeric, 3),
      ('SAFEPARENT_Q069', 'D', 'Let them experiment freely', 0::numeric, 4),
      ('SAFEPARENT_Q070', 'A', 'Responds consistently and warmly', 1::numeric, 1),
      ('SAFEPARENT_Q070', 'B', 'Avoids comforting the child', 0::numeric, 2),
      ('SAFEPARENT_Q070', 'C', 'Shows affection only during achievements', 0::numeric, 3),
      ('SAFEPARENT_Q070', 'D', 'Uses emotional distance as discipline', 0::numeric, 4),
      ('SAFEPARENT_Q071', 'A', 'Criticising personality traits', 0::numeric, 1),
      ('SAFEPARENT_Q071', 'B', 'Highlighting mistakes without guidance', 0::numeric, 2),
      ('SAFEPARENT_Q071', 'C', 'Specific behaviours and improvement strategies', 1::numeric, 3),
      ('SAFEPARENT_Q071', 'D', 'Publicly pointing out errors', 0::numeric, 4),
      ('SAFEPARENT_Q072', 'A', 'Dictating all solutions', 0::numeric, 1),
      ('SAFEPARENT_Q072', 'B', 'Ignoring the child''s perspective', 0::numeric, 2),
      ('SAFEPARENT_Q072', 'C', 'Working together to find fair solutions', 1::numeric, 3),
      ('SAFEPARENT_Q072', 'D', 'Letting the child decide everything', 0::numeric, 4),
      ('SAFEPARENT_Q073', 'A', 'Unlimited access', 0::numeric, 1),
      ('SAFEPARENT_Q073', 'B', 'No screens ever', 0::numeric, 2),
      ('SAFEPARENT_Q073', 'C', 'Clear limits and breaks for physical activity', 1::numeric, 3),
      ('SAFEPARENT_Q073', 'D', 'Using screens only as punishment', 0::numeric, 4),
      ('SAFEPARENT_Q074', 'A', 'Warmth, communication, and shared time', 1::numeric, 1),
      ('SAFEPARENT_Q074', 'B', 'Frequent criticism', 0::numeric, 2),
      ('SAFEPARENT_Q074', 'C', 'Ignoring emotional needs', 0::numeric, 3),
      ('SAFEPARENT_Q074', 'D', 'Rigid control', 0::numeric, 4),
      ('SAFEPARENT_Q075', 'A', 'Explain why the rule exists and discuss consequences', 1::numeric, 1),
      ('SAFEPARENT_Q075', 'B', 'Punish them without explanation', 0::numeric, 2),
      ('SAFEPARENT_Q075', 'C', 'Ignore the behaviour', 0::numeric, 3),
      ('SAFEPARENT_Q075', 'D', 'React with anger', 0::numeric, 4),
      ('SAFEPARENT_Q076', 'A', 'Discussing feelings and perspectives', 1::numeric, 1),
      ('SAFEPARENT_Q076', 'B', 'Avoiding emotional conversations', 0::numeric, 2),
      ('SAFEPARENT_Q076', 'C', 'Mocking emotional reactions', 0::numeric, 3),
      ('SAFEPARENT_Q076', 'D', 'Discouraging emotional expression', 0::numeric, 4)
  ) as option(item_key, value, label, score, display_order)
)
insert into public.assessment_item_response_options (item_id, label, value, score, display_order)
select items.id, options.label, options.value, options.score, options.display_order
from items
join options on options.item_key = items.item_key
on conflict (item_id, value) do update
set
  label = excluded.label,
  score = excluded.score,
  display_order = excluded.display_order;
