revoke execute on function public.ai_learning_has_blocking_governance_finding(text, uuid) from authenticated;
revoke execute on function public.assert_program_start_gate(uuid, uuid, text) from authenticated;
revoke execute on function public.can_activate_platform_tenant_feature(uuid) from authenticated;
revoke execute on function public.can_approve_ai_change_request(uuid) from authenticated;
revoke execute on function public.can_close_case_v19(uuid) from authenticated;
revoke execute on function public.can_close_child_support_request(uuid) from authenticated;
revoke execute on function public.can_close_community_referral(uuid) from authenticated;
revoke execute on function public.can_complete_child_lesson(uuid) from authenticated;
revoke execute on function public.can_complete_learning_challenge(uuid, uuid) from authenticated;
revoke execute on function public.can_complete_learning_course(uuid, uuid) from authenticated;
revoke execute on function public.can_complete_learning_lesson(uuid) from authenticated;
revoke execute on function public.can_delete_platform_tenant(uuid) from authenticated;
revoke execute on function public.can_export_ai_learning_data(uuid) from authenticated;
revoke execute on function public.can_export_court_assessment_package(uuid) from authenticated;
revoke execute on function public.can_export_evidence(uuid) from authenticated;
revoke execute on function public.can_export_platform_tenant_data(uuid) from authenticated;
revoke execute on function public.can_finalize_assessment_record(uuid) from authenticated;
revoke execute on function public.can_include_ai_learning_candidate(uuid) from authenticated;
revoke execute on function public.can_include_item_in_ai_dataset(uuid) from authenticated;
revoke execute on function public.can_issue_learning_certificate(uuid, uuid, uuid) from authenticated;
revoke execute on function public.can_issue_structured_learning_certificate(uuid) from authenticated;
revoke execute on function public.can_operationally_activate_ai_service(uuid, uuid) from authenticated;
revoke execute on function public.can_override_child_sharing_for_safety(uuid, text, text) from authenticated;
revoke execute on function public.can_publish_learning_lesson(uuid) from authenticated;
revoke execute on function public.can_release_ai_deployment(uuid) from authenticated;
revoke execute on function public.can_release_ai_explanation(uuid) from authenticated;
revoke execute on function public.can_release_ai_learning_change(uuid) from authenticated;
revoke execute on function public.can_rely_on_reunification_readiness(uuid) from authenticated;
revoke execute on function public.can_retire_ai_model_version(uuid) from authenticated;
revoke execute on function public.can_route_ai_workload(uuid, uuid) from authenticated;
revoke execute on function public.can_send_community_referral(uuid) from authenticated;
revoke execute on function public.can_share_child_content(uuid, text, text, text, text) from authenticated;
revoke execute on function public.can_start_ai_canary_release(uuid) from authenticated;
revoke execute on function public.can_use_ai_learning_personalisation(uuid, uuid) from authenticated;
revoke execute on function public.case_setup_ready_for_program(uuid) from authenticated;
revoke execute on function public.current_family_member_ids() from authenticated;
revoke execute on function public.current_security_role() from authenticated;
revoke execute on function public.current_tenant_ids() from authenticated;
revoke execute on function public.is_online_learning_permitted(uuid) from authenticated;
revoke execute on function public.profile_ready_for_program(uuid) from authenticated;
revoke execute on function public.should_escalate_child_request(uuid) from authenticated;
