create table if not exists public.evidence_ai_analyses (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.platform_tenants(id) on delete restrict,
  evidence_record_id uuid not null references public.evidence_records(id) on delete cascade,
  evidence_file_id uuid references public.evidence_files(id) on delete set null,
  analysis_reference text not null,
  analysis_type text not null,
  model_reference text,
  model_version text,
  confidence_score numeric not null default 0,
  analysis_summary text,
  protective_factors jsonb not null default '[]'::jsonb,
  risk_factors jsonb not null default '[]'::jsonb,
  detected_objects jsonb not null default '[]'::jsonb,
  detected_people jsonb not null default '[]'::jsonb,
  detected_hazards jsonb not null default '[]'::jsonb,
  speech_transcript text,
  sentiment_summary text,
  recommended_human_review boolean not null default true,
  worker_override jsonb,
  review_status text not null default 'pending_human_review',
  reviewer_user_id uuid references auth.users(id) on delete set null,
  analysed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (tenant_id, analysis_reference),
  constraint evidence_ai_analyses_confidence_check check (confidence_score >= 0 and confidence_score <= 1)
);
