alter table public.activities add constraint activities_pkey PRIMARY KEY (id);
alter table public.casefiles add constraint casefiles_pkey PRIMARY KEY (case_id);
alter table public.curriculum add constraint curriculum_pkey PRIMARY KEY (curriculum_id);
alter table public.documents add constraint documents_pkey PRIMARY KEY (id);
alter table public.evidence add constraint evidence_pkey PRIMARY KEY (id);
alter table public.forensic_scores add constraint forensic_scores_pkey PRIMARY KEY (score_id);
alter table public.messaging_messages add constraint messaging_messages_pkey PRIMARY KEY (id);
alter table public.messaging_thread_summaries add constraint messaging_thread_summaries_pkey PRIMARY KEY (id);
alter table public.messaging_threads add constraint messaging_threads_pkey PRIMARY KEY (id);
alter table public.parents add constraint parents_pkey PRIMARY KEY (parent_id);
alter table public.progress add constraint progress_pkey PRIMARY KEY (id);
alter table public.user_settings add constraint user_settings_pkey PRIMARY KEY (id);
alter table public.user_video_progress add constraint user_video_progress_pkey PRIMARY KEY (id);
alter table public.verified_people_directory add constraint verified_people_directory_pkey PRIMARY KEY (id);
alter table public.video_admin_audit_events add constraint video_admin_audit_events_pkey PRIMARY KEY (id);
alter table public.video_assessment_attempts add constraint video_assessment_attempts_pkey PRIMARY KEY (id);
alter table public.video_case_assignment_audit_events add constraint video_case_assignment_audit_events_pkey PRIMARY KEY (id);
alter table public.video_case_assignments add constraint video_case_assignments_pkey PRIMARY KEY (id);
alter table public.video_curriculum_mappings add constraint video_curriculum_mappings_pkey PRIMARY KEY (id);
alter table public.video_deployment_checks add constraint video_deployment_checks_pkey PRIMARY KEY (id);
alter table public.video_feature_flags add constraint video_feature_flags_pkey PRIMARY KEY (flag_key);
alter table public.video_lesson_contents add constraint video_lesson_contents_pkey PRIMARY KEY (id);
alter table public.video_notification_delivery_attempts add constraint video_notification_delivery_attempts_pkey PRIMARY KEY (id);
alter table public.video_notification_devices add constraint video_notification_devices_pkey PRIMARY KEY (id);
alter table public.video_notification_preferences add constraint video_notification_preferences_pkey PRIMARY KEY (user_id);
alter table public.video_practice_tasks add constraint video_practice_tasks_pkey PRIMARY KEY (id);
alter table public.video_progress_report_snapshots add constraint video_progress_report_snapshots_pkey PRIMARY KEY (id);
alter table public.video_providers add constraint video_providers_pkey PRIMARY KEY (id);
alter table public.video_reflections add constraint video_reflections_pkey PRIMARY KEY (id);
alter table public.video_release_records add constraint video_release_records_pkey PRIMARY KEY (id);
alter table public.video_report_access_authorities add constraint video_report_access_authorities_pkey PRIMARY KEY (id);
alter table public.video_report_access_grants add constraint video_report_access_grants_pkey PRIMARY KEY (id);
alter table public.video_report_attestations add constraint video_report_attestations_pkey PRIMARY KEY (id);
alter table public.video_report_delivery_events add constraint video_report_delivery_events_pkey PRIMARY KEY (id);
alter table public.video_report_delivery_purposes add constraint video_report_delivery_purposes_pkey PRIMARY KEY (id);
alter table public.video_report_dispute_responses add constraint video_report_dispute_responses_pkey PRIMARY KEY (id);
alter table public.video_report_disputes add constraint video_report_disputes_pkey PRIMARY KEY (id);
alter table public.video_report_export_audit_events add constraint video_report_export_audit_events_pkey PRIMARY KEY (id);
alter table public.video_report_export_files add constraint video_report_export_files_pkey PRIMARY KEY (id);
alter table public.video_report_legal_holds add constraint video_report_legal_holds_pkey PRIMARY KEY (id);
alter table public.video_report_retention_rules add constraint video_report_retention_rules_pkey PRIMARY KEY (id);
alter table public.video_report_review_history add constraint video_report_review_history_pkey PRIMARY KEY (id);
alter table public.video_report_review_requests add constraint video_report_review_requests_pkey PRIMARY KEY (id);
alter table public.video_report_review_schedules add constraint video_report_review_schedules_pkey PRIMARY KEY (id);
alter table public.video_report_system_health_events add constraint video_report_system_health_events_pkey PRIMARY KEY (id);
alter table public.video_report_verification_codes add constraint video_report_verification_codes_pkey PRIMARY KEY (id);
alter table public.video_resources add constraint video_resources_pkey PRIMARY KEY (id);
alter table public.video_watch_events add constraint video_watch_events_pkey PRIMARY KEY (id);
alter table public.weeks add constraint weeks_pkey PRIMARY KEY (id);
alter table public.messaging_thread_summaries add constraint messaging_thread_summaries_thread_id_key UNIQUE (thread_id);
alter table public.user_video_progress add constraint user_video_progress_user_id_video_resource_id_key UNIQUE (user_id, video_resource_id);
alter table public.video_curriculum_mappings add constraint video_curriculum_mappings_video_resource_id_lesson_title_key UNIQUE (video_resource_id, lesson_title);
alter table public.video_lesson_contents add constraint video_lesson_contents_video_resource_id_key UNIQUE (video_resource_id);
alter table public.video_notification_devices add constraint video_notification_devices_expo_push_token_key UNIQUE (expo_push_token);
alter table public.video_providers add constraint video_providers_name_key UNIQUE (name);
alter table public.video_report_access_grants add constraint video_report_access_grants_parent_user_id_reviewer_user_id__key UNIQUE (parent_user_id, reviewer_user_id, access_scope);
alter table public.video_report_delivery_purposes add constraint video_report_delivery_purposes_purpose_code_key UNIQUE (purpose_code);
alter table public.video_report_export_files add constraint video_report_export_files_storage_bucket_storage_path_key UNIQUE (storage_bucket, storage_path);
alter table public.video_report_retention_rules add constraint video_report_retention_rules_rule_code_key UNIQUE (rule_code);
alter table public.video_report_verification_codes add constraint video_report_verification_codes_verification_code_key UNIQUE (verification_code);
alter table public.video_resources add constraint video_resources_provider_id_title_key UNIQUE (provider_id, title);
alter table public.casefiles add constraint casefiles_account_mode_check CHECK (account_mode = ANY (ARRAY['single'::text, 'joint'::text, 'dual'::text]));
alter table public.curriculum add constraint curriculum_homework_status_check CHECK (homework_status = ANY (ARRAY['pending'::text, 'completed'::text]));
alter table public.forensic_scores add constraint forensic_scores_risk_level_check CHECK (risk_level = ANY (ARRAY['low'::text, 'moderate'::text, 'high'::text]));
alter table public.user_video_progress add constraint user_video_progress_max_watch_percentage_check CHECK (max_watch_percentage >= 0 AND max_watch_percentage <= 100);
alter table public.verified_people_directory add constraint verified_people_directory_role_check CHECK (role = ANY (ARRAY['parent'::text, 'worker'::text, 'lawyer'::text, 'professional'::text]));
alter table public.video_assessment_attempts add constraint video_assessment_attempts_score_check CHECK (score >= 0 AND score <= 100);
alter table public.video_case_assignments add constraint video_case_assignments_access_scope_check CHECK (access_scope = ANY (ARRAY['video_progress'::text, 'video_progress_and_evidence'::text]));
alter table public.video_case_assignments add constraint video_case_assignments_assignment_status_check CHECK (assignment_status = ANY (ARRAY['active'::text, 'ended'::text, 'suspended'::text]));
alter table public.video_curriculum_mappings add constraint video_curriculum_mappings_watch_percentage_required_check CHECK (watch_percentage_required >= 0 AND watch_percentage_required <= 100);
alter table public.video_deployment_checks add constraint video_deployment_checks_check_status_check CHECK (check_status = ANY (ARRAY['pending'::text, 'passed'::text, 'failed'::text]));
alter table public.video_lesson_contents add constraint video_lesson_contents_five_questions CHECK (jsonb_array_length(assessment_questions) = 5);
alter table public.video_progress_report_snapshots add constraint video_progress_report_snapshots_evidence_access_scope_check CHECK (evidence_access_scope = ANY (ARRAY['video_progress'::text, 'video_progress_and_evidence'::text]));
alter table public.video_release_records add constraint video_release_records_release_status_check CHECK (release_status = ANY (ARRAY['planned'::text, 'staging'::text, 'approved'::text, 'deployed'::text, 'rolled_back'::text]));
alter table public.video_report_access_authorities add constraint video_report_access_authorities_access_scope_check CHECK (access_scope = ANY (ARRAY['video_progress'::text, 'video_progress_and_evidence'::text]));
alter table public.video_report_access_authorities add constraint video_report_access_authorities_authority_type_check CHECK (authority_type = ANY (ARRAY['parent_consent'::text, 'parent_requested_professional'::text, 'organisational_case_assignment'::text, 'court_order'::text, 'statutory_authority'::text, 'emergency_safety_authority'::text]));
alter table public.video_report_access_grants add constraint video_report_access_grants_access_scope_check CHECK (access_scope = ANY (ARRAY['video_progress'::text, 'video_progress_and_evidence'::text]));
alter table public.video_report_dispute_responses add constraint video_report_dispute_responses_decision_check CHECK (decision = ANY (ARRAY['upheld'::text, 'partially_upheld'::text, 'not_upheld'::text]));
alter table public.video_report_disputes add constraint video_report_disputes_dispute_type_check CHECK (dispute_type = ANY (ARRAY['factual_error'::text, 'missing_context'::text, 'incorrect_attribution'::text, 'privacy_access'::text, 'assessment_concern'::text]));
alter table public.video_report_disputes add constraint video_report_disputes_status_check CHECK (status = ANY (ARRAY['submitted'::text, 'under_review'::text, 'upheld'::text, 'partially_upheld'::text, 'not_upheld'::text, 'closed'::text]));
alter table public.video_report_export_files add constraint video_report_export_files_export_type_check CHECK (export_type = ANY (ARRAY['pdf'::text, 'case_package_zip'::text]));
alter table public.video_report_review_requests add constraint video_report_review_requests_review_status_check CHECK (review_status = ANY (ARRAY['submitted'::text, 'in_review'::text, 'approved'::text, 'rejected'::text, 'changes_requested'::text]));
alter table public.video_report_review_schedules add constraint video_report_review_schedules_cadence_check CHECK (cadence = ANY (ARRAY['weekly'::text, 'fortnightly'::text, 'monthly'::text, 'quarterly'::text]));
alter table public.video_report_system_health_events add constraint video_report_system_health_events_severity_check CHECK (severity = ANY (ARRAY['info'::text, 'warning'::text, 'critical'::text]));
alter table public.video_resources add constraint video_resources_attribution_review_status_check CHECK (attribution_review_status = ANY (ARRAY['pending'::text, 'approved'::text, 'changes_required'::text]));
alter table public.video_resources add constraint video_resources_clinical_review_status_check CHECK (clinical_review_status = ANY (ARRAY['pending'::text, 'approved'::text, 'changes_required'::text]));
alter table public.video_resources add constraint video_resources_cultural_review_status_check CHECK (cultural_review_status = ANY (ARRAY['pending'::text, 'approved'::text, 'changes_required'::text]));
alter table public.video_resources add constraint video_resources_download_permission_check CHECK (download_permission = false);
alter table public.video_resources add constraint video_resources_editing_permission_check CHECK (editing_permission = false);
alter table public.video_resources add constraint video_resources_embed_code_status_check CHECK (embed_code_status = ANY (ARRAY['missing'::text, 'pending_review'::text, 'verified'::text, 'failed'::text]));
alter table public.video_resources add constraint video_resources_publication_status_check CHECK (publication_status = ANY (ARRAY['draft'::text, 'approved'::text, 'published'::text, 'retired'::text]));
alter table public.video_resources add constraint video_resources_publish_requires_captions CHECK (publication_status <> 'published'::text OR captions_verified = true);
alter table public.video_resources add constraint video_resources_publish_requires_embed_url CHECK (publication_status <> 'published'::text OR embed_url IS NOT NULL);
alter table public.video_resources add constraint video_resources_publish_requires_review CHECK (publication_status <> 'published'::text OR licence_checked_at IS NOT NULL);
alter table public.video_resources add constraint video_resources_publish_requires_verified_embed CHECK (publication_status <> 'published'::text OR embed_code_status = 'verified'::text);
alter table public.video_resources add constraint video_resources_rehosting_permission_check CHECK (rehosting_permission = false);
alter table public.video_resources add constraint video_resources_requires_five_questions CHECK (jsonb_array_length(knowledge_check) = 5);
alter table public.video_watch_events add constraint video_watch_events_event_type_check CHECK (event_type = ANY (ARRAY['loaded'::text, 'play'::text, 'pause'::text, 'timeupdate'::text, 'seeking'::text, 'ended'::text]));
alter table public.video_watch_events add constraint video_watch_events_watch_percentage_check CHECK (watch_percentage >= 0 AND watch_percentage <= 100);