-- Seed SafeSteps parenting domain-structured fill-in-the-blank responsibility/independence items 201-240 and 401-440.

with instrument as (select id from public.assessment_instruments where slug = 'safesteps-parenting-domain-fill-blank-v1')
insert into public.assessment_domains (instrument_id, name, description, weight, display_order)
select instrument.id, domain.name, domain.description, 1::numeric, domain.display_order
from instrument
cross join (
  values
    ('responsibility_independence', 'Weighted fill-in-the-blank items for responsibility, independence, planning, follow-through, and child-led problem solving.', 4)
) as domain(name, description, display_order)
on conflict (instrument_id, name) do update
set description = excluded.description, weight = excluded.weight, display_order = excluded.display_order;

with instrument as (select id from public.assessment_instruments where slug = 'safesteps-parenting-domain-fill-blank-v1'),
domain_lookup as (select d.id, d.name from public.assessment_domains d join instrument i on i.id = d.instrument_id)
insert into public.assessment_items (domain_id, item_key, prompt, item_type, weight, max_value, display_order, is_critical)
select domain_lookup.id, item.item_key, item.prompt, 'multiple_choice', item.weight, null, item.display_order, false
from domain_lookup
join (
  values
('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q201', 'I encourage independence by letting my child ______ their own learning tasks.', 3::numeric, 201),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q202', 'I teach responsibility by having my child ______ their own weekly goals.', 3::numeric, 202),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q203', 'I help my child grow independence by encouraging them to ______ new learning challenges.', 3::numeric, 203),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q204', 'I support responsibility by teaching my child to ______ their own progress logs.', 2::numeric, 204),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q205', 'I encourage independence by letting my child ______ their own project ideas.', 3::numeric, 205),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q206', 'I teach responsibility by having my child ______ their own daily checklist.', 3::numeric, 206),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q207', 'I help my child grow independence by encouraging them to ______ their own study plans.', 3::numeric, 207),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q208', 'I support responsibility by teaching my child to ______ their own learning materials.', 2::numeric, 208),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q209', 'I encourage independence by letting my child ______ their own project timelines.', 3::numeric, 209),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q210', 'I teach responsibility by having my child ______ their own weekly progress.', 2::numeric, 210),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q211', 'I help my child learn responsibility by teaching them to ______ their own assignments.', 3::numeric, 211),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q212', 'I encourage independence by letting my child ______ their own study environment.', 2::numeric, 212),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q213', 'I teach responsibility by having my child ______ their own learning schedule.', 3::numeric, 213),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q214', 'I help my child grow independence by encouraging them to ______ new academic challenges.', 3::numeric, 214),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q215', 'I support responsibility by teaching my child to ______ their own learning goals.', 3::numeric, 215),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q216', 'I encourage independence by letting my child ______ their own learning strategies.', 3::numeric, 216),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q217', 'I teach responsibility by having my child ______ their own progress charts.', 2::numeric, 217),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q218', 'I encourage independence by letting my child ______ their own learning tools.', 2::numeric, 218),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q219', 'I teach responsibility by having my child ______ their own academic tasks.', 3::numeric, 219),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q220', 'I encourage independence by letting my child ______ their own learning challenges.', 3::numeric, 220),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q221', 'I help my child learn responsibility by teaching them to ______ their own learning materials.', 2::numeric, 221),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q222', 'I encourage independence by letting my child ______ their own learning plans.', 3::numeric, 222),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q223', 'I teach responsibility by having my child ______ their own learning progress.', 2::numeric, 223),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q224', 'I help my child grow independence by encouraging them to ______ new learning opportunities.', 3::numeric, 224),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q225', 'I support responsibility by teaching my child to ______ their own learning tasks.', 3::numeric, 225),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q226', 'I encourage independence by letting my child ______ their own learning goals.', 3::numeric, 226),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q227', 'I teach responsibility by having my child ______ their own learning schedule weekly.', 2::numeric, 227),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q228', 'I encourage independence by letting my child ______ their own learning strategies.', 2::numeric, 228),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q229', 'I teach responsibility by having my child ______ their own learning goals monthly.', 3::numeric, 229),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q230', 'I encourage independence by letting my child ______ their own learning tasks independently.', 3::numeric, 230),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q231', 'I help my child learn responsibility by teaching them to ______ their own learning materials weekly.', 2::numeric, 231),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q232', 'I encourage independence by letting my child ______ their own learning projects.', 3::numeric, 232),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q233', 'I teach responsibility by having my child ______ their own learning deadlines monthly.', 3::numeric, 233),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q234', 'I help my child grow independence by encouraging them to ______ new learning tasks.', 3::numeric, 234),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q235', 'I support responsibility by teaching my child to ______ their own learning progress monthly.', 2::numeric, 235),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q236', 'I encourage independence by letting my child ______ their own learning ideas.', 3::numeric, 236),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q237', 'I teach responsibility by having my child ______ their own learning priorities monthly.', 2::numeric, 237),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q238', 'I encourage independence by letting my child ______ their own learning challenges monthly.', 3::numeric, 238),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q239', 'I teach responsibility by having my child ______ their own learning commitments monthly.', 3::numeric, 239),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q240', 'I encourage independence by letting my child ______ their own learning routines monthly.', 2::numeric, 240),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q401', 'I encourage independence by letting my child ______ their own daily learning tasks.', 3::numeric, 401),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q402', 'I teach responsibility by having my child ______ their own weekly learning goals.', 3::numeric, 402),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q403', 'I help my child grow independence by encouraging them to ______ new learning challenges.', 3::numeric, 403),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q404', 'I support responsibility by teaching my child to ______ their own progress logs.', 2::numeric, 404),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q405', 'I encourage independence by letting my child ______ their own project ideas.', 3::numeric, 405),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q406', 'I teach responsibility by having my child ______ their own daily checklist.', 3::numeric, 406),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q407', 'I help my child grow independence by encouraging them to ______ their own study plans.', 3::numeric, 407),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q408', 'I support responsibility by teaching my child to ______ their own learning materials.', 2::numeric, 408),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q409', 'I encourage independence by letting my child ______ their own project timelines.', 3::numeric, 409),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q410', 'I teach responsibility by having my child ______ their own weekly progress.', 2::numeric, 410),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q411', 'I help my child learn responsibility by teaching them to ______ their own assignments.', 3::numeric, 411),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q412', 'I encourage independence by letting my child ______ their own study environment.', 2::numeric, 412),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q413', 'I teach responsibility by having my child ______ their own learning schedule.', 3::numeric, 413),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q414', 'I help my child grow independence by encouraging them to ______ new academic challenges.', 3::numeric, 414),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q415', 'I support responsibility by teaching my child to ______ their own learning goals.', 3::numeric, 415),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q416', 'I encourage independence by letting my child ______ their own learning strategies.', 3::numeric, 416),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q417', 'I teach responsibility by having my child ______ their own progress charts.', 2::numeric, 417),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q418', 'I encourage independence by letting my child ______ their own learning tools.', 2::numeric, 418),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q419', 'I teach responsibility by having my child ______ their own academic tasks.', 3::numeric, 419),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q420', 'I encourage independence by letting my child ______ their own learning challenges.', 3::numeric, 420),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q421', 'I help my child learn responsibility by teaching them to ______ their own learning materials.', 2::numeric, 421),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q422', 'I encourage independence by letting my child ______ their own learning plans.', 3::numeric, 422),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q423', 'I teach responsibility by having my child ______ their own learning progress.', 2::numeric, 423),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q424', 'I help my child grow independence by encouraging them to ______ new learning opportunities.', 3::numeric, 424),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q425', 'I support responsibility by teaching my child to ______ their own learning tasks.', 3::numeric, 425),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q426', 'I encourage independence by letting my child ______ their own learning goals.', 3::numeric, 426),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q427', 'I teach responsibility by having my child ______ their own learning schedule weekly.', 2::numeric, 427),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q428', 'I encourage independence by letting my child ______ their own learning strategies.', 2::numeric, 428),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q429', 'I teach responsibility by having my child ______ their own learning goals monthly.', 3::numeric, 429),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q430', 'I encourage independence by letting my child ______ their own learning tasks independently.', 3::numeric, 430),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q431', 'I help my child learn responsibility by teaching them to ______ their own learning materials weekly.', 2::numeric, 431),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q432', 'I encourage independence by letting my child ______ their own learning projects.', 3::numeric, 432),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q433', 'I teach responsibility by having my child ______ their own learning deadlines monthly.', 3::numeric, 433),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q434', 'I help my child grow independence by encouraging them to ______ new learning tasks.', 3::numeric, 434),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q435', 'I support responsibility by teaching my child to ______ their own learning progress monthly.', 2::numeric, 435),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q436', 'I encourage independence by letting my child ______ their own learning ideas.', 3::numeric, 436),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q437', 'I teach responsibility by having my child ______ their own learning priorities monthly.', 2::numeric, 437),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q438', 'I encourage independence by letting my child ______ their own learning challenges monthly.', 3::numeric, 438),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q439', 'I teach responsibility by having my child ______ their own learning commitments monthly.', 3::numeric, 439),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q440', 'I encourage independence by letting my child ______ their own learning routines monthly.', 2::numeric, 440)
) as item(domain_name, item_key, prompt, weight, display_order) on item.domain_name = domain_lookup.name
on conflict (domain_id, item_key) do update
set prompt = excluded.prompt, item_type = excluded.item_type, weight = excluded.weight, max_value = excluded.max_value, display_order = excluded.display_order, is_critical = excluded.is_critical;

with instrument as (select id from public.assessment_instruments where slug = 'safesteps-parenting-domain-fill-blank-v1'),
items as (select ai.id, ai.item_key from public.assessment_items ai join public.assessment_domains ad on ad.id = ai.domain_id join instrument i on i.id = ad.instrument_id),
options as (select * from (
  values
('SAFEPARENT_DOMAIN_FILL_Q201', 'A', 'choose', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q201', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q201', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q201', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q202', 'A', 'set', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q202', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q202', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q202', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q203', 'A', 'attempt', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q203', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q203', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q203', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q204', 'A', 'update', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q204', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q204', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q204', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q205', 'A', 'develop', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q205', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q205', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q205', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q206', 'A', 'complete', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q206', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q206', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q206', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q207', 'A', 'create', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q207', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q207', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q207', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q208', 'A', 'organize', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q208', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q208', 'C', 'lose', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q208', 'D', 'avoid', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q209', 'A', 'set', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q209', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q209', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q209', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q210', 'A', 'review', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q210', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q210', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q210', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q211', 'A', 'complete', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q211', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q211', 'C', 'delay', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q211', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q212', 'A', 'set up', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q212', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q212', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q212', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q213', 'A', 'manage', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q213', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q213', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q213', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q214', 'A', 'try', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q214', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q214', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q214', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q215', 'A', 'set', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q215', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q215', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q215', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q216', 'A', 'choose', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q216', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q216', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q216', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q217', 'A', 'update', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q217', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q217', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q217', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q218', 'A', 'select', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q218', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q218', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q218', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q219', 'A', 'prioritize', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q219', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q219', 'C', 'delay', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q219', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q220', 'A', 'face', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q220', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q220', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q220', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q221', 'A', 'prepare', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q221', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q221', 'C', 'lose', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q221', 'D', 'avoid', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q222', 'A', 'design', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q222', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q222', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q222', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q223', 'A', 'track', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q223', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q223', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q223', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q224', 'A', 'explore', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q224', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q224', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q224', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q225', 'A', 'complete', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q225', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q225', 'C', 'delay', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q225', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q226', 'A', 'evaluate', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q226', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q226', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q226', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q227', 'A', 'review', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q227', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q227', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q227', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q228', 'A', 'test', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q228', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q228', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q228', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q229', 'A', 'set', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q229', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q229', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q229', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q230', 'A', 'attempt', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q230', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q230', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q230', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q231', 'A', 'organize', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q231', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q231', 'C', 'lose', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q231', 'D', 'avoid', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q232', 'A', 'start', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q232', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q232', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q232', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q233', 'A', 'set', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q233', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q233', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q233', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q234', 'A', 'try', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q234', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q234', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q234', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q235', 'A', 'review', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q235', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q235', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q235', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q236', 'A', 'develop', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q236', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q236', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q236', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q237', 'A', 'set', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q237', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q237', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q237', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q238', 'A', 'face', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q238', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q238', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q238', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q239', 'A', 'honor', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q239', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q239', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q239', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q240', 'A', 'build', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q240', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q240', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q240', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q401', 'A', 'choose', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q401', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q401', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q401', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q402', 'A', 'set', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q402', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q402', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q402', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q403', 'A', 'attempt', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q403', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q403', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q403', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q404', 'A', 'update', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q404', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q404', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q404', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q405', 'A', 'develop', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q405', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q405', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q405', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q406', 'A', 'complete', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q406', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q406', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q406', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q407', 'A', 'create', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q407', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q407', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q407', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q408', 'A', 'organize', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q408', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q408', 'C', 'lose', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q408', 'D', 'avoid', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q409', 'A', 'set', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q409', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q409', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q409', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q410', 'A', 'review', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q410', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q410', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q410', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q411', 'A', 'complete', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q411', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q411', 'C', 'delay', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q411', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q412', 'A', 'set up', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q412', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q412', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q412', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q413', 'A', 'manage', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q413', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q413', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q413', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q414', 'A', 'try', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q414', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q414', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q414', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q415', 'A', 'set', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q415', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q415', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q415', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q416', 'A', 'choose', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q416', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q416', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q416', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q417', 'A', 'update', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q417', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q417', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q417', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q418', 'A', 'select', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q418', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q418', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q418', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q419', 'A', 'prioritize', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q419', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q419', 'C', 'delay', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q419', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q420', 'A', 'face', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q420', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q420', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q420', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q421', 'A', 'prepare', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q421', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q421', 'C', 'lose', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q421', 'D', 'avoid', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q422', 'A', 'design', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q422', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q422', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q422', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q423', 'A', 'track', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q423', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q423', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q423', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q424', 'A', 'explore', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q424', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q424', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q424', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q425', 'A', 'complete', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q425', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q425', 'C', 'delay', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q425', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q426', 'A', 'evaluate', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q426', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q426', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q426', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q427', 'A', 'review', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q427', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q427', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q427', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q428', 'A', 'test', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q428', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q428', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q428', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q429', 'A', 'set', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q429', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q429', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q429', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q430', 'A', 'attempt', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q430', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q430', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q430', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q431', 'A', 'organize', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q431', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q431', 'C', 'lose', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q431', 'D', 'avoid', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q432', 'A', 'start', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q432', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q432', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q432', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q433', 'A', 'set', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q433', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q433', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q433', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q434', 'A', 'try', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q434', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q434', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q434', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q435', 'A', 'review', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q435', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q435', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q435', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q436', 'A', 'develop', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q436', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q436', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q436', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q437', 'A', 'set', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q437', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q437', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q437', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q438', 'A', 'face', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q438', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q438', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q438', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q439', 'A', 'honor', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q439', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q439', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q439', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q440', 'A', 'build', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q440', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q440', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q440', 'D', 'ignore', 0::numeric, 4)
) as option(item_key, value, label, score, display_order))
insert into public.assessment_item_response_options (item_id, label, value, score, display_order)
select items.id, options.label, options.value, options.score, options.display_order
from items
join options on options.item_key = items.item_key
on conflict (item_id, value) do update
set label = excluded.label, score = excluded.score, display_order = excluded.display_order;