create table if not exists public.case_plan_goals (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.platform_tenants(id) on delete restrict,
  case_plan_id uuid not null references public.case_plans(id) on delete cascade,
  goal_reference text not null,
  goal_title text not null,
  goal_description text not null,
  goal_domain text not null,
  goal_status text not null default 'not_started',
  priority_level text not null default 'standard',
  baseline_summary text,
  success_definition text not null,
  target_date date,
  completed_at timestamptz,
  owner_type text not null,
  owner_reference uuid,
  child_voice_summary text,
  parent_view_summary text,
  worker_view_summary text,
  sequence_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, goal_reference)
);

create table if not exists public.case_plan_actions (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.platform_tenants(id) on delete restrict,
  case_plan_goal_id uuid not null references public.case_plan_goals(id) on delete cascade,
  action_reference text not null,
  action_title text not null,
  action_description text not null,
  action_type text not null,
  assigned_to_type text not null,
  assigned_to_reference uuid,
  action_status text not null default 'not_started',
  due_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  completion_evidence_required boolean not null default false,
  completion_evidence_summary text,
  sequence_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, action_reference)
);
