-- Seed SafeSteps parenting domain-structured fill-in-the-blank responsibility/independence items 101-141.

with instrument as (select id from public.assessment_instruments where slug = 'safesteps-parenting-domain-fill-blank-v1')
insert into public.assessment_domains (instrument_id, name, description, weight, display_order)
select instrument.id, domain.name, domain.description, 1::numeric, domain.display_order
from instrument
cross join (
  values
    ('responsibility_independence', 'Weighted fill-in-the-blank items for responsibility, independence, planning, follow-through, and child-led problem solving.', 4)
) as domain(name, description, display_order)
on conflict (instrument_id, name) do update
set description = excluded.description, weight = excluded.weight, display_order = excluded.display_order;

with instrument as (select id from public.assessment_instruments where slug = 'safesteps-parenting-domain-fill-blank-v1'),
domain_lookup as (select d.id, d.name from public.assessment_domains d join instrument i on i.id = d.instrument_id)
insert into public.assessment_items (domain_id, item_key, prompt, item_type, weight, max_value, display_order, is_critical)
select domain_lookup.id, item.item_key, item.prompt, 'multiple_choice', item.weight, null, item.display_order, false
from domain_lookup
join (
  values
('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q101', 'I encourage independence by letting my child ______ their own projects.', 3::numeric, 101),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q102', 'I teach responsibility by having my child ______ their own deadlines.', 3::numeric, 102),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q103', 'I help my child grow independence by encouraging them to ______ new tasks.', 2::numeric, 103),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q104', 'I support responsibility by teaching my child to ______ their own progress.', 3::numeric, 104),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q105', 'I encourage independence by letting my child ______ their own solutions.', 3::numeric, 105),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q106', 'I teach responsibility by having my child ______ their own workspace.', 2::numeric, 106),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q107', 'I help my child grow independence by encouraging them to ______ their own routines.', 3::numeric, 107),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q108', 'I support responsibility by teaching my child to ______ their own tasks daily.', 3::numeric, 108),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q109', 'I encourage independence by letting my child ______ their own ideas.', 2::numeric, 109),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q110', 'I teach responsibility by having my child ______ their own commitments.', 3::numeric, 110),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q111', 'I help my child learn responsibility by teaching them to ______ their own belongings.', 2::numeric, 111),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q112', 'I encourage independence by letting my child ______ their own plans.', 3::numeric, 112),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q113', 'I teach responsibility by having my child ______ their own priorities.', 2::numeric, 113),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q114', 'I help my child grow independence by encouraging them to ______ new experiences.', 3::numeric, 114),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q115', 'I support responsibility by teaching my child to ______ their own routines.', 3::numeric, 115),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q116', 'I encourage independence by letting my child ______ their own solutions.', 2::numeric, 116),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q117', 'I teach responsibility by having my child ______ their own progress.', 2::numeric, 117),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q118', 'I encourage independence by letting my child ______ their own tasks.', 3::numeric, 118),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q119', 'I teach responsibility by having my child ______ their own goals.', 3::numeric, 119),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q120', 'I encourage independence by letting my child ______ their own decisions.', 3::numeric, 120),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q121', 'I help my child learn responsibility by teaching them to ______ their own time.', 3::numeric, 121),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q122', 'I encourage independence by letting my child ______ their own ideas.', 3::numeric, 122),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q123', 'I teach responsibility by having my child ______ their own tasks.', 3::numeric, 123),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q124', 'I help my child grow independence by encouraging them to ______ new challenges.', 3::numeric, 124),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q125', 'I support responsibility by teaching my child to ______ their own commitments.', 3::numeric, 125),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q126', 'I encourage independence by letting my child ______ their own routines.', 2::numeric, 126),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q127', 'I teach responsibility by having my child ______ their own progress daily.', 2::numeric, 127),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q128', 'I encourage independence by letting my child ______ their own plans.', 3::numeric, 128),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q129', 'I teach responsibility by having my child ______ their own priorities daily.', 2::numeric, 129),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q130', 'I encourage independence by letting my child ______ their own tasks without help.', 3::numeric, 130),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q131', 'I help my child learn responsibility by teaching them to ______ their own belongings daily.', 2::numeric, 131),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q132', 'I encourage independence by letting my child ______ their own solutions.', 3::numeric, 132),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q133', 'I teach responsibility by having my child ______ their own workspace daily.', 2::numeric, 133),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q134', 'I help my child grow independence by encouraging them to ______ new tasks.', 3::numeric, 134),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q135', 'I support responsibility by teaching my child to ______ their own progress weekly.', 2::numeric, 135),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q136', 'I encourage independence by letting my child ______ their own ideas.', 2::numeric, 136),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q137', 'I teach responsibility by having my child ______ their own deadlines weekly.', 3::numeric, 137),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q138', 'I help my child grow independence by encouraging them to ______ new experiences.', 3::numeric, 138),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q139', 'I support responsibility by teaching my child to ______ their own commitments weekly.', 3::numeric, 139),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q140', 'I encourage independence by letting my child ______ their own routines weekly.', 2::numeric, 140),
    ('responsibility_independence', 'SAFEPARENT_DOMAIN_FILL_Q141', 'I teach responsibility by having my child ______ their own progress monthly.', 2::numeric, 141)
) as item(domain_name, item_key, prompt, weight, display_order) on item.domain_name = domain_lookup.name
on conflict (domain_id, item_key) do update
set prompt = excluded.prompt, item_type = excluded.item_type, weight = excluded.weight, max_value = excluded.max_value, display_order = excluded.display_order, is_critical = excluded.is_critical;

with instrument as (select id from public.assessment_instruments where slug = 'safesteps-parenting-domain-fill-blank-v1'),
items as (select ai.id, ai.item_key from public.assessment_items ai join public.assessment_domains ad on ad.id = ai.domain_id join instrument i on i.id = ad.instrument_id),
options as (select * from (
  values
('SAFEPARENT_DOMAIN_FILL_Q101', 'A', 'start', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q101', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q101', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q101', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q102', 'A', 'set', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q102', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q102', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q102', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q103', 'A', 'attempt', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q103', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q103', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q103', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q104', 'A', 'monitor', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q104', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q104', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q104', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q105', 'A', 'design', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q105', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q105', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q105', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q106', 'A', 'organize', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q106', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q106', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q106', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q107', 'A', 'create', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q107', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q107', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q107', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q108', 'A', 'complete', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q108', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q108', 'C', 'delay', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q108', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q109', 'A', 'explore', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q109', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q109', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q109', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q110', 'A', 'honor', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q110', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q110', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q110', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q111', 'A', 'care for', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q111', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q111', 'C', 'lose', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q111', 'D', 'avoid', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q112', 'A', 'build', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q112', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q112', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q112', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q113', 'A', 'set', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q113', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q113', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q113', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q114', 'A', 'try', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q114', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q114', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q114', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q115', 'A', 'follow', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q115', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q115', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q115', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q116', 'A', 'test', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q116', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q116', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q116', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q117', 'A', 'review', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q117', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q117', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q117', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q118', 'A', 'plan', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q118', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q118', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q118', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q119', 'A', 'work toward', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q119', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q119', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q119', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q120', 'A', 'evaluate', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q120', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q120', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q120', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q121', 'A', 'manage', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q121', 'B', 'waste', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q121', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q121', 'D', 'avoid', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q122', 'A', 'develop', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q122', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q122', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q122', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q123', 'A', 'prioritize', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q123', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q123', 'C', 'delay', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q123', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q124', 'A', 'face', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q124', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q124', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q124', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q125', 'A', 'honor', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q125', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q125', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q125', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q126', 'A', 'build', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q126', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q126', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q126', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q127', 'A', 'track', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q127', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q127', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q127', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q128', 'A', 'create', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q128', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q128', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q128', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q129', 'A', 'set', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q129', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q129', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q129', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q130', 'A', 'attempt', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q130', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q130', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q130', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q131', 'A', 'organize', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q131', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q131', 'C', 'lose', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q131', 'D', 'avoid', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q132', 'A', 'design', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q132', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q132', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q132', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q133', 'A', 'organize', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q133', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q133', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q133', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q134', 'A', 'try', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q134', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q134', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q134', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q135', 'A', 'review', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q135', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q135', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q135', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q136', 'A', 'explore', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q136', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q136', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q136', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q137', 'A', 'set', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q137', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q137', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q137', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q138', 'A', 'try', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q138', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q138', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q138', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q139', 'A', 'honor', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q139', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q139', 'C', 'ignore', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q139', 'D', 'delay', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q140', 'A', 'build', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q140', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q140', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q140', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_DOMAIN_FILL_Q141', 'A', 'review', 1::numeric, 1),
      ('SAFEPARENT_DOMAIN_FILL_Q141', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_DOMAIN_FILL_Q141', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_DOMAIN_FILL_Q141', 'D', 'delay', 0::numeric, 4)
) as option(item_key, value, label, score, display_order))
insert into public.assessment_item_response_options (item_id, label, value, score, display_order)
select items.id, options.label, options.value, options.score, options.display_order
from items
join options on options.item_key = items.item_key
on conflict (item_id, value) do update
set label = excluded.label, score = excluded.score, display_order = excluded.display_order;