alter table public.curriculum add constraint curriculum_case_id_fkey FOREIGN KEY (case_id) REFERENCES casefiles(case_id) ON DELETE CASCADE;
alter table public.documents add constraint documents_family_id_fkey FOREIGN KEY (family_id) REFERENCES families(id);
alter table public.documents add constraint documents_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
alter table public.forensic_scores add constraint forensic_scores_case_id_fkey FOREIGN KEY (case_id) REFERENCES casefiles(case_id) ON DELETE CASCADE;
alter table public.forensic_scores add constraint forensic_scores_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES parents(parent_id) ON DELETE CASCADE;
alter table public.messaging_messages add constraint messaging_messages_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES messaging_threads(id) ON DELETE CASCADE;
alter table public.messaging_thread_summaries add constraint messaging_thread_summaries_last_message_id_fkey FOREIGN KEY (last_message_id) REFERENCES messaging_messages(id) ON DELETE SET NULL;
alter table public.messaging_thread_summaries add constraint messaging_thread_summaries_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES messaging_threads(id) ON DELETE CASCADE;
alter table public.parents add constraint parents_case_id_fkey FOREIGN KEY (case_id) REFERENCES casefiles(case_id) ON DELETE CASCADE;
alter table public.user_video_progress add constraint user_video_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.user_video_progress add constraint user_video_progress_video_resource_id_fkey FOREIGN KEY (video_resource_id) REFERENCES video_resources(id) ON DELETE CASCADE;
alter table public.verified_people_directory add constraint verified_people_directory_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_admin_audit_events add constraint video_admin_audit_events_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_admin_audit_events add constraint video_admin_audit_events_video_resource_id_fkey FOREIGN KEY (video_resource_id) REFERENCES video_resources(id) ON DELETE SET NULL;
alter table public.video_assessment_attempts add constraint video_assessment_attempts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.video_assessment_attempts add constraint video_assessment_attempts_video_resource_id_fkey FOREIGN KEY (video_resource_id) REFERENCES video_resources(id) ON DELETE CASCADE;
alter table public.video_case_assignment_audit_events add constraint video_case_assignment_audit_events_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_case_assignment_audit_events add constraint video_case_assignment_audit_events_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES video_case_assignments(id) ON DELETE SET NULL;
alter table public.video_case_assignments add constraint video_case_assignments_access_grant_id_fkey FOREIGN KEY (access_grant_id) REFERENCES video_report_access_grants(id) ON DELETE SET NULL;
alter table public.video_case_assignments add constraint video_case_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_case_assignments add constraint video_case_assignments_ended_by_fkey FOREIGN KEY (ended_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_case_assignments add constraint video_case_assignments_parent_user_id_fkey FOREIGN KEY (parent_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.video_case_assignments add constraint video_case_assignments_worker_user_id_fkey FOREIGN KEY (worker_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.video_curriculum_mappings add constraint video_curriculum_mappings_video_resource_id_fkey FOREIGN KEY (video_resource_id) REFERENCES video_resources(id) ON DELETE CASCADE;
alter table public.video_lesson_contents add constraint video_lesson_contents_video_resource_id_fkey FOREIGN KEY (video_resource_id) REFERENCES video_resources(id) ON DELETE CASCADE;
alter table public.video_notification_delivery_attempts add constraint video_notification_delivery_attempts_device_id_fkey FOREIGN KEY (device_id) REFERENCES video_notification_devices(id) ON DELETE SET NULL;
alter table public.video_notification_delivery_attempts add constraint video_notification_delivery_attempts_outbox_id_fkey FOREIGN KEY (outbox_id) REFERENCES video_notification_outbox(id) ON DELETE CASCADE;
alter table public.video_notification_devices add constraint video_notification_devices_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.video_notification_preferences add constraint video_notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.video_practice_tasks add constraint video_practice_tasks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.video_practice_tasks add constraint video_practice_tasks_video_resource_id_fkey FOREIGN KEY (video_resource_id) REFERENCES video_resources(id) ON DELETE CASCADE;
alter table public.video_progress_report_snapshots add constraint video_progress_report_snapshots_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_progress_report_snapshots add constraint video_progress_report_snapshots_parent_user_id_fkey FOREIGN KEY (parent_user_id) REFERENCES auth.users(id) ON DELETE RESTRICT;
alter table public.video_reflections add constraint video_reflections_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.video_reflections add constraint video_reflections_video_resource_id_fkey FOREIGN KEY (video_resource_id) REFERENCES video_resources(id) ON DELETE CASCADE;
alter table public.video_release_records add constraint video_release_records_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_report_access_authorities add constraint video_report_access_authorities_authorised_user_id_fkey FOREIGN KEY (authorised_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.video_report_access_authorities add constraint video_report_access_authorities_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_report_access_authorities add constraint video_report_access_authorities_parent_user_id_fkey FOREIGN KEY (parent_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.video_report_access_authorities add constraint video_report_access_authorities_withdrawn_by_fkey FOREIGN KEY (withdrawn_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_report_access_grants add constraint video_report_access_grants_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_report_access_grants add constraint video_report_access_grants_parent_user_id_fkey FOREIGN KEY (parent_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.video_report_access_grants add constraint video_report_access_grants_reviewer_user_id_fkey FOREIGN KEY (reviewer_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.video_report_attestations add constraint video_report_attestations_export_file_id_fkey FOREIGN KEY (export_file_id) REFERENCES video_report_export_files(id) ON DELETE SET NULL;
alter table public.video_report_attestations add constraint video_report_attestations_revoked_by_fkey FOREIGN KEY (revoked_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_report_attestations add constraint video_report_attestations_signer_user_id_fkey FOREIGN KEY (signer_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_report_attestations add constraint video_report_attestations_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES video_progress_report_snapshots(id) ON DELETE RESTRICT;
alter table public.video_report_delivery_events add constraint video_report_delivery_events_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES video_report_deliveries(id) ON DELETE CASCADE;
alter table public.video_report_dispute_responses add constraint video_report_dispute_responses_dispute_id_fkey FOREIGN KEY (dispute_id) REFERENCES video_report_disputes(id) ON DELETE CASCADE;
alter table public.video_report_dispute_responses add constraint video_report_dispute_responses_reviewer_user_id_fkey FOREIGN KEY (reviewer_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_report_dispute_responses add constraint video_report_dispute_responses_superseding_snapshot_id_fkey FOREIGN KEY (superseding_snapshot_id) REFERENCES video_progress_report_snapshots(id) ON DELETE RESTRICT;
alter table public.video_report_disputes add constraint video_report_disputes_parent_user_id_fkey FOREIGN KEY (parent_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.video_report_disputes add constraint video_report_disputes_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES video_progress_report_snapshots(id) ON DELETE RESTRICT;
alter table public.video_report_disputes add constraint video_report_disputes_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_report_export_audit_events add constraint video_report_export_audit_events_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_report_export_audit_events add constraint video_report_export_audit_events_export_file_id_fkey FOREIGN KEY (export_file_id) REFERENCES video_report_export_files(id) ON DELETE SET NULL;
alter table public.video_report_export_audit_events add constraint video_report_export_audit_events_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES video_progress_report_snapshots(id) ON DELETE SET NULL;
alter table public.video_report_export_files add constraint video_report_export_files_parent_user_id_fkey FOREIGN KEY (parent_user_id) REFERENCES auth.users(id) ON DELETE RESTRICT;
alter table public.video_report_export_files add constraint video_report_export_files_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_report_export_files add constraint video_report_export_files_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES video_progress_report_snapshots(id) ON DELETE RESTRICT;
alter table public.video_report_legal_holds add constraint video_report_legal_holds_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_report_legal_holds add constraint video_report_legal_holds_parent_user_id_fkey FOREIGN KEY (parent_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.video_report_legal_holds add constraint video_report_legal_holds_released_by_fkey FOREIGN KEY (released_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_report_legal_holds add constraint video_report_legal_holds_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES video_progress_report_snapshots(id) ON DELETE RESTRICT;
alter table public.video_report_review_history add constraint video_report_review_history_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_report_review_history add constraint video_report_review_history_review_request_id_fkey FOREIGN KEY (review_request_id) REFERENCES video_report_review_requests(id) ON DELETE CASCADE;
alter table public.video_report_review_requests add constraint video_report_review_requests_assigned_reviewer_id_fkey FOREIGN KEY (assigned_reviewer_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_report_review_requests add constraint video_report_review_requests_decided_by_fkey FOREIGN KEY (decided_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_report_review_requests add constraint video_report_review_requests_parent_user_id_fkey FOREIGN KEY (parent_user_id) REFERENCES auth.users(id) ON DELETE RESTRICT;
alter table public.video_report_review_requests add constraint video_report_review_requests_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES video_progress_report_snapshots(id) ON DELETE RESTRICT;
alter table public.video_report_review_requests add constraint video_report_review_requests_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_report_review_schedules add constraint video_report_review_schedules_assigned_reviewer_id_fkey FOREIGN KEY (assigned_reviewer_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_report_review_schedules add constraint video_report_review_schedules_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_report_review_schedules add constraint video_report_review_schedules_parent_user_id_fkey FOREIGN KEY (parent_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.video_report_verification_codes add constraint video_report_verification_codes_export_file_id_fkey FOREIGN KEY (export_file_id) REFERENCES video_report_export_files(id) ON DELETE SET NULL;
alter table public.video_report_verification_codes add constraint video_report_verification_codes_revoked_by_fkey FOREIGN KEY (revoked_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.video_report_verification_codes add constraint video_report_verification_codes_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES video_progress_report_snapshots(id) ON DELETE RESTRICT;
alter table public.video_resources add constraint video_resources_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES video_providers(id);
alter table public.video_watch_events add constraint video_watch_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.video_watch_events add constraint video_watch_events_video_resource_id_fkey FOREIGN KEY (video_resource_id) REFERENCES video_resources(id) ON DELETE CASCADE;
alter table public.weeks add constraint weeks_program_id_fkey FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE CASCADE;