-- Seed expanded SafeSteps fill-in-the-blank parenting quiz items Q021-Q120.

with instrument as (
  select id from public.assessment_instruments where slug = 'safesteps-parenting-fill-blank-v1'
)
insert into public.assessment_domains (instrument_id, name, description, weight, display_order)
select instrument.id, domain.name, domain.description, 1::numeric, domain.display_order
from instrument
cross join (
  values
    ('responsibility_building', 'Chores, tasks, belongings, and responsibility practice.', 16),
    ('resilience_support', 'Trying again, facing challenges, and resilience.', 17),
    ('learning_environment', 'Positive educational materials, opportunities, and environments.', 18)
) as domain(name, description, display_order)
on conflict (instrument_id, name) do update
set
  description = excluded.description,
  weight = excluded.weight,
  display_order = excluded.display_order;

with instrument as (
  select id from public.assessment_instruments where slug = 'safesteps-parenting-fill-blank-v1'
),
domain_lookup as (
  select d.id, d.name
  from public.assessment_domains d
  join instrument i on i.id = d.instrument_id
)
insert into public.assessment_items (
  domain_id,
  item_key,
  prompt,
  item_type,
  weight,
  max_value,
  display_order,
  is_critical
)
select domain_lookup.id, item.item_key, item.prompt, 'multiple_choice', 1::numeric, null, item.display_order, false
from domain_lookup
join (
  values
    ('emotional_regulation', 'SAFEPARENT_FILL_Q021', 'When my child is frustrated, I help them ______.', 21),
    ('communication_style', 'SAFEPARENT_FILL_Q022', 'I show my child respect by ______ their opinions.', 22),
    ('attention_support', 'SAFEPARENT_FILL_Q023', 'I help my child stay organized by creating ______ routines.', 23),
    ('motivation_support', 'SAFEPARENT_FILL_Q024', 'I support my child’s confidence by praising their ______.', 24),
    ('responsibility_building', 'SAFEPARENT_FILL_Q025', 'I teach responsibility by letting my child ______ tasks.', 25),
    ('boundaries_consistency', 'SAFEPARENT_FILL_Q026', 'I help my child feel safe by keeping rules ______.', 26),
    ('parent_child_relationship', 'SAFEPARENT_FILL_Q027', 'I strengthen connection by spending ______ time with my child.', 27),
    ('empathy_development', 'SAFEPARENT_FILL_Q028', 'I help my child learn empathy by modeling ______.', 28),
    ('emotional_attunement', 'SAFEPARENT_FILL_Q029', 'I support emotional growth by teaching ______ strategies.', 29),
    ('motivation_support', 'SAFEPARENT_FILL_Q030', 'I help my child stay calm by encouraging them to ______.', 30),
    ('attachment_security', 'SAFEPARENT_FILL_Q031', 'I build trust by being ______ with my child.', 31),
    ('problem_solving', 'SAFEPARENT_FILL_Q032', 'I help my child solve problems by ______ together.', 32),
    ('learning_environment', 'SAFEPARENT_FILL_Q033', 'I support learning by asking my child ______.', 33),
    ('emotional_attunement', 'SAFEPARENT_FILL_Q034', 'I help my child feel heard by ______ their feelings.', 34),
    ('motivation_support', 'SAFEPARENT_FILL_Q035', 'I encourage independence by letting my child ______.', 35),
    ('positive_discipline', 'SAFEPARENT_FILL_Q036', 'I respond to mistakes with ______.', 36),
    ('attention_support', 'SAFEPARENT_FILL_Q037', 'I help my child stay focused by reducing ______.', 37),
    ('emotional_regulation', 'SAFEPARENT_FILL_Q038', 'I teach emotional regulation by practicing ______.', 38),
    ('parent_child_relationship', 'SAFEPARENT_FILL_Q039', 'I help my child feel supported by being ______.', 39),
    ('motivation_support', 'SAFEPARENT_FILL_Q040', 'I encourage problem‑solving by asking my child to ______.', 40),
    ('stress_management', 'SAFEPARENT_FILL_Q041', 'I help my child manage stress by teaching them to ______.', 41),
    ('communication_style', 'SAFEPARENT_FILL_Q042', 'I model good communication by speaking ______.', 42),
    ('motivation_support', 'SAFEPARENT_FILL_Q043', 'I help my child feel valued by ______ their achievements.', 43),
    ('motivation_support', 'SAFEPARENT_FILL_Q044', 'I support resilience by encouraging my child to ______.', 44),
    ('boundaries_consistency', 'SAFEPARENT_FILL_Q045', 'I help my child understand limits by setting ______ boundaries.', 45),
    ('responsibility_building', 'SAFEPARENT_FILL_Q046', 'I teach responsibility by having my child ______ chores.', 46),
    ('emotional_attunement', 'SAFEPARENT_FILL_Q047', 'I help my child feel understood by ______ their perspective.', 47),
    ('motivation_support', 'SAFEPARENT_FILL_Q048', 'I encourage learning by providing ______ opportunities.', 48),
    ('emotional_regulation', 'SAFEPARENT_FILL_Q049', 'I help my child regulate emotions by practicing ______ together.', 49),
    ('parent_child_relationship', 'SAFEPARENT_FILL_Q050', 'I show support by being ______ during difficult moments.', 50),
    ('motivation_support', 'SAFEPARENT_FILL_Q051', 'I help my child stay motivated by setting ______ goals.', 51),
    ('empathy_development', 'SAFEPARENT_FILL_Q052', 'I teach kindness by ______ others.', 52),
    ('motivation_support', 'SAFEPARENT_FILL_Q053', 'I help my child feel confident by encouraging ______.', 53),
    ('boundaries_consistency', 'SAFEPARENT_FILL_Q054', 'I support emotional safety by being ______.', 54),
    ('positive_discipline', 'SAFEPARENT_FILL_Q055', 'I help my child learn patience by practicing ______.', 55),
    ('responsibility_building', 'SAFEPARENT_FILL_Q056', 'I encourage responsibility by having my child ______ tasks.', 56),
    ('attachment_security', 'SAFEPARENT_FILL_Q057', 'I help my child feel secure by maintaining ______ routines.', 57),
    ('problem_solving', 'SAFEPARENT_FILL_Q058', 'I teach problem‑solving by asking my child to ______.', 58),
    ('emotional_regulation', 'SAFEPARENT_FILL_Q059', 'I help my child manage frustration by teaching ______ skills.', 59),
    ('parent_child_relationship', 'SAFEPARENT_FILL_Q060', 'I show care by being ______ when my child needs help.', 60),
    ('emotional_regulation', 'SAFEPARENT_FILL_Q061', 'I help my child stay calm by modeling ______.', 61),
    ('motivation_support', 'SAFEPARENT_FILL_Q062', 'I encourage growth by praising ______.', 62),
    ('communication_style', 'SAFEPARENT_FILL_Q063', 'I help my child feel respected by ______ them.', 63),
    ('responsibility_building', 'SAFEPARENT_FILL_Q064', 'I teach responsibility by giving my child ______ tasks.', 64),
    ('motivation_support', 'SAFEPARENT_FILL_Q065', 'I help my child feel supported by offering ______.', 65),
    ('emotional_attunement', 'SAFEPARENT_FILL_Q066', 'I teach emotional awareness by naming ______.', 66),
    ('emotional_attunement', 'SAFEPARENT_FILL_Q067', 'I help my child stay engaged by making activities ______.', 67),
    ('motivation_support', 'SAFEPARENT_FILL_Q068', 'I encourage independence by letting my child ______ decisions.', 68),
    ('stress_management', 'SAFEPARENT_FILL_Q069', 'I help my child feel calm by practicing ______.', 69),
    ('learning_environment', 'SAFEPARENT_FILL_Q070', 'I support learning by creating a ______ environment.', 70),
    ('motivation_support', 'SAFEPARENT_FILL_Q071', 'I help my child feel confident by ______ their strengths.', 71),
    ('motivation_support', 'SAFEPARENT_FILL_Q072', 'I teach patience by encouraging my child to ______.', 72),
    ('boundaries_consistency', 'SAFEPARENT_FILL_Q073', 'I help my child feel safe by being ______.', 73),
    ('communication_style', 'SAFEPARENT_FILL_Q074', 'I encourage communication by asking my child to ______.', 74),
    ('emotional_regulation', 'SAFEPARENT_FILL_Q075', 'I help my child manage anger by teaching ______.', 75),
    ('resilience_support', 'SAFEPARENT_FILL_Q076', 'I support resilience by helping my child ______ challenges.', 76),
    ('empathy_development', 'SAFEPARENT_FILL_Q077', 'I teach empathy by ______ others.', 77),
    ('attention_support', 'SAFEPARENT_FILL_Q078', 'I help my child stay organized by using ______ lists.', 78),
    ('responsibility_building', 'SAFEPARENT_FILL_Q079', 'I encourage responsibility by having my child ______ their belongings.', 79),
    ('parent_child_relationship', 'SAFEPARENT_FILL_Q080', 'I help my child feel supported by offering ______ guidance.', 80),
    ('boundaries_consistency', 'SAFEPARENT_FILL_Q081', 'I teach emotional safety by being ______.', 81),
    ('problem_solving', 'SAFEPARENT_FILL_Q082', 'I help my child learn problem‑solving by ______ options.', 82),
    ('motivation_support', 'SAFEPARENT_FILL_Q083', 'I encourage learning by providing ______ materials.', 83),
    ('motivation_support', 'SAFEPARENT_FILL_Q084', 'I help my child feel confident by ______ their progress.', 84),
    ('responsibility_building', 'SAFEPARENT_FILL_Q085', 'I teach responsibility by having my child ______ tasks on time.', 85),
    ('stress_management', 'SAFEPARENT_FILL_Q086', 'I help my child feel calm by practicing ______ together.', 86),
    ('motivation_support', 'SAFEPARENT_FILL_Q087', 'I encourage independence by letting my child ______ choices.', 87),
    ('emotional_attunement', 'SAFEPARENT_FILL_Q088', 'I help my child feel heard by ______ their words.', 88),
    ('emotional_regulation', 'SAFEPARENT_FILL_Q089', 'I teach emotional regulation by modeling ______.', 89),
    ('attention_support', 'SAFEPARENT_FILL_Q090', 'I help my child stay focused by creating ______ spaces.', 90),
    ('motivation_support', 'SAFEPARENT_FILL_Q091', 'I encourage resilience by teaching my child to ______.', 91),
    ('boundaries_consistency', 'SAFEPARENT_FILL_Q092', 'I help my child feel secure by maintaining ______ expectations.', 92),
    ('empathy_development', 'SAFEPARENT_FILL_Q093', 'I teach kindness by ______ positive behavior.', 93),
    ('stress_management', 'SAFEPARENT_FILL_Q094', 'I help my child manage stress by teaching ______ techniques.', 94),
    ('communication_style', 'SAFEPARENT_FILL_Q095', 'I encourage communication by creating ______ conversations.', 95),
    ('parent_child_relationship', 'SAFEPARENT_FILL_Q096', 'I help my child feel supported by being ______.', 96),
    ('responsibility_building', 'SAFEPARENT_FILL_Q097', 'I teach responsibility by having my child ______ their tasks.', 97),
    ('emotional_regulation', 'SAFEPARENT_FILL_Q098', 'I help my child feel calm by practicing ______ exercises.', 98),
    ('motivation_support', 'SAFEPARENT_FILL_Q099', 'I encourage independence by letting my child ______ solutions.', 99),
    ('motivation_support', 'SAFEPARENT_FILL_Q100', 'I help my child feel valued by ______ their efforts.', 100),
    ('emotional_attunement', 'SAFEPARENT_FILL_Q101', 'I teach emotional awareness by discussing ______.', 101),
    ('motivation_support', 'SAFEPARENT_FILL_Q102', 'I help my child stay motivated by setting ______ goals.', 102),
    ('motivation_support', 'SAFEPARENT_FILL_Q103', 'I encourage learning by providing ______ experiences.', 103),
    ('motivation_support', 'SAFEPARENT_FILL_Q104', 'I help my child feel confident by ______ their achievements.', 104),
    ('responsibility_building', 'SAFEPARENT_FILL_Q105', 'I teach responsibility by having my child ______ their duties.', 105),
    ('stress_management', 'SAFEPARENT_FILL_Q106', 'I help my child feel calm by practicing ______.', 106),
    ('motivation_support', 'SAFEPARENT_FILL_Q107', 'I encourage independence by letting my child ______ tasks.', 107),
    ('emotional_attunement', 'SAFEPARENT_FILL_Q108', 'I help my child feel heard by ______ their concerns.', 108),
    ('emotional_regulation', 'SAFEPARENT_FILL_Q109', 'I teach emotional regulation by practicing ______.', 109),
    ('attention_support', 'SAFEPARENT_FILL_Q110', 'I help my child stay focused by reducing ______.', 110),
    ('motivation_support', 'SAFEPARENT_FILL_Q111', 'I encourage resilience by teaching my child to ______.', 111),
    ('attachment_security', 'SAFEPARENT_FILL_Q112', 'I help my child feel secure by keeping routines ______.', 112),
    ('empathy_development', 'SAFEPARENT_FILL_Q113', 'I teach kindness by ______ positive actions.', 113),
    ('stress_management', 'SAFEPARENT_FILL_Q114', 'I help my child manage stress by teaching ______.', 114),
    ('communication_style', 'SAFEPARENT_FILL_Q115', 'I encourage communication by creating ______ discussions.', 115),
    ('motivation_support', 'SAFEPARENT_FILL_Q116', 'I help my child feel supported by offering ______.', 116),
    ('responsibility_building', 'SAFEPARENT_FILL_Q117', 'I teach responsibility by having my child ______ tasks independently.', 117),
    ('emotional_regulation', 'SAFEPARENT_FILL_Q118', 'I help my child feel calm by practicing ______ techniques.', 118),
    ('motivation_support', 'SAFEPARENT_FILL_Q119', 'I encourage independence by letting my child ______ choices.', 119),
    ('motivation_support', 'SAFEPARENT_FILL_Q120', 'I help my child feel valued by ______ their progress.', 120)
) as item(domain_name, item_key, prompt, display_order)
  on item.domain_name = domain_lookup.name
on conflict (domain_id, item_key) do update
set
  prompt = excluded.prompt,
  item_type = excluded.item_type,
  weight = excluded.weight,
  max_value = excluded.max_value,
  display_order = excluded.display_order,
  is_critical = excluded.is_critical;

with instrument as (
  select id from public.assessment_instruments where slug = 'safesteps-parenting-fill-blank-v1'
),
items as (
  select ai.id, ai.item_key
  from public.assessment_items ai
  join public.assessment_domains ad on ad.id = ai.domain_id
  join instrument i on i.id = ad.instrument_id
),
options as (
  select *
  from (
    values
      ('SAFEPARENT_FILL_Q021', 'A', 'calm down', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q021', 'B', 'ignore it', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q021', 'C', 'get louder', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q021', 'D', 'walk away', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q022', 'A', 'listening to', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q022', 'B', 'dismissing', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q022', 'C', 'mocking', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q022', 'D', 'avoiding', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q023', 'A', 'daily', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q023', 'B', 'random', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q023', 'C', 'inconsistent', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q023', 'D', 'rare', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q024', 'A', 'effort', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q024', 'B', 'appearance', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q024', 'C', 'possessions', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q024', 'D', 'mistakes only', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q025', 'A', 'attempt', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q025', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q025', 'C', 'complain about', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q025', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q026', 'A', 'consistent', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q026', 'B', 'unclear', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q026', 'C', 'changing', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q026', 'D', 'rare', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q027', 'A', 'quality', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q027', 'B', 'no', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q027', 'C', 'distracted', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q027', 'D', 'inconsistent', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q028', 'A', 'kindness', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q028', 'B', 'sarcasm', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q028', 'C', 'criticism', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q028', 'D', 'avoidance', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q029', 'A', 'coping', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q029', 'B', 'denial', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q029', 'C', 'blaming', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q029', 'D', 'avoidance', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q030', 'A', 'breathe', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q030', 'B', 'shout', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q030', 'C', 'hide', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q030', 'D', 'blame', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q031', 'A', 'reliable', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q031', 'B', 'unpredictable', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q031', 'C', 'dismissive', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q031', 'D', 'inconsistent', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q032', 'A', 'talking', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q032', 'B', 'avoiding', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q032', 'C', 'guessing', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q032', 'D', 'punishing', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q033', 'A', 'questions', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q033', 'B', 'nothing', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q033', 'C', 'to stop', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q033', 'D', 'to avoid challenges', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q034', 'A', 'validating', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q034', 'B', 'ignoring', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q034', 'C', 'mocking', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q034', 'D', 'minimizing', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q035', 'A', 'make choices', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q035', 'B', 'depend fully', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q035', 'C', 'avoid decisions', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q035', 'D', 'copy others', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q036', 'A', 'patience', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q036', 'B', 'anger', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q036', 'C', 'shame', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q036', 'D', 'silence', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q037', 'A', 'distractions', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q037', 'B', 'support', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q037', 'C', 'structure', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q037', 'D', 'encouragement', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q038', 'A', 'calming techniques', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q038', 'B', 'yelling', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q038', 'C', 'avoidance', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q038', 'D', 'denial', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q039', 'A', 'present', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q039', 'B', 'distracted', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q039', 'C', 'unavailable', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q039', 'D', 'dismissive', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q040', 'A', 'think it through', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q040', 'B', 'give up', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q040', 'C', 'avoid it', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q040', 'D', 'blame others', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q041', 'A', 'take breaks', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q041', 'B', 'ignore it', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q041', 'C', 'panic', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q041', 'D', 'avoid responsibility', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q042', 'A', 'calmly', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q042', 'B', 'angrily', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q042', 'C', 'sarcastically', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q042', 'D', 'unclearly', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q043', 'A', 'celebrating', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q043', 'B', 'ignoring', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q043', 'C', 'criticizing', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q043', 'D', 'downplaying', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q044', 'A', 'try again', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q044', 'B', 'quit', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q044', 'C', 'avoid challenges', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q044', 'D', 'blame others', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q045', 'A', 'clear', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q045', 'B', 'confusing', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q045', 'C', 'inconsistent', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q045', 'D', 'none', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q046', 'A', 'complete', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q046', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q046', 'C', 'complain about', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q046', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q047', 'A', 'acknowledging', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q047', 'B', 'rejecting', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q047', 'C', 'mocking', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q047', 'D', 'ignoring', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q048', 'A', 'growth', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q048', 'B', 'none', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q048', 'C', 'stressful', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q048', 'D', 'avoidance', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q049', 'A', 'breathing', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q049', 'B', 'yelling', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q049', 'C', 'blaming', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q049', 'D', 'avoiding', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q050', 'A', 'patient', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q050', 'B', 'angry', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q050', 'C', 'dismissive', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q050', 'D', 'silent', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q051', 'A', 'achievable', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q051', 'B', 'impossible', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q051', 'C', 'unclear', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q051', 'D', 'none', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q052', 'A', 'helping', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q052', 'B', 'mocking', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q052', 'C', 'criticizing', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q052', 'D', 'avoiding', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q053', 'A', 'effort', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q053', 'B', 'perfection', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q053', 'C', 'comparison', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q053', 'D', 'avoidance', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q054', 'A', 'consistent', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q054', 'B', 'unpredictable', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q054', 'C', 'harsh', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q054', 'D', 'dismissive', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q055', 'A', 'waiting', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q055', 'B', 'complaining', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q055', 'C', 'rushing', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q055', 'D', 'avoiding', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q056', 'A', 'finish', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q056', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q056', 'C', 'complain', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q056', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q057', 'A', 'stable', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q057', 'B', 'chaotic', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q057', 'C', 'rare', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q057', 'D', 'random', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q058', 'A', 'think', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q058', 'B', 'panic', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q058', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q058', 'D', 'blame', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q059', 'A', 'coping', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q059', 'B', 'denial', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q059', 'C', 'avoidance', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q059', 'D', 'blaming', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q060', 'A', 'available', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q060', 'B', 'unavailable', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q060', 'C', 'dismissive', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q060', 'D', 'angry', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q061', 'A', 'self‑control', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q061', 'B', 'anger', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q061', 'C', 'panic', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q061', 'D', 'avoidance', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q062', 'A', 'progress', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q062', 'B', 'perfection only', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q062', 'C', 'appearance', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q062', 'D', 'possessions', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q063', 'A', 'listening to', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q063', 'B', 'interrupting', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q063', 'C', 'mocking', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q063', 'D', 'ignoring', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q064', 'A', 'age‑appropriate', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q064', 'B', 'overwhelming', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q064', 'C', 'none', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q064', 'D', 'confusing', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q065', 'A', 'encouragement', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q065', 'B', 'criticism', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q065', 'C', 'silence', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q065', 'D', 'avoidance', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q066', 'A', 'feelings', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q066', 'B', 'objects', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q066', 'C', 'random words', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q066', 'D', 'nothing', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q067', 'A', 'fun', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q067', 'B', 'boring', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q067', 'C', 'stressful', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q067', 'D', 'confusing', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q068', 'A', 'make', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q068', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q068', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q068', 'D', 'copy others', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q069', 'A', 'relaxation', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q069', 'B', 'panic', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q069', 'C', 'avoidance', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q069', 'D', 'blaming', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q070', 'A', 'positive', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q070', 'B', 'chaotic', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q070', 'C', 'stressful', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q070', 'D', 'distracting', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q071', 'A', 'highlighting', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q071', 'B', 'ignoring', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q071', 'C', 'criticizing', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q071', 'D', 'downplaying', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q072', 'A', 'wait', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q072', 'B', 'rush', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q072', 'C', 'complain', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q072', 'D', 'avoid', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q073', 'A', 'consistent', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q073', 'B', 'harsh', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q073', 'C', 'unpredictable', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q073', 'D', 'dismissive', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q074', 'A', 'share', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q074', 'B', 'hide', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q074', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q074', 'D', 'stay silent', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q075', 'A', 'calming skills', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q075', 'B', 'shouting', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q075', 'C', 'blaming', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q075', 'D', 'avoiding', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q076', 'A', 'face', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q076', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q076', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q076', 'D', 'blame', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q077', 'A', 'helping', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q077', 'B', 'mocking', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q077', 'C', 'criticizing', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q077', 'D', 'avoiding', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q078', 'A', 'check', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q078', 'B', 'random', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q078', 'C', 'confusing', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q078', 'D', 'none', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q079', 'A', 'care for', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q079', 'B', 'ignore', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q079', 'C', 'lose', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q079', 'D', 'avoid', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q080', 'A', 'gentle', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q080', 'B', 'harsh', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q080', 'C', 'none', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q080', 'D', 'confusing', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q081', 'A', 'calm', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q081', 'B', 'angry', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q081', 'C', 'dismissive', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q081', 'D', 'unpredictable', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q082', 'A', 'exploring', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q082', 'B', 'avoiding', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q082', 'C', 'guessing', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q082', 'D', 'blaming', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q083', 'A', 'educational', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q083', 'B', 'irrelevant', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q083', 'C', 'none', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q083', 'D', 'confusing', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q084', 'A', 'celebrating', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q084', 'B', 'ignoring', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q084', 'C', 'criticizing', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q084', 'D', 'downplaying', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q085', 'A', 'complete', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q085', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q085', 'C', 'delay', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q085', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q086', 'A', 'mindfulness', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q086', 'B', 'panic', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q086', 'C', 'avoidance', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q086', 'D', 'blaming', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q087', 'A', 'make', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q087', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q087', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q087', 'D', 'copy others', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q088', 'A', 'listening to', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q088', 'B', 'interrupting', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q088', 'C', 'mocking', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q088', 'D', 'ignoring', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q089', 'A', 'calm behavior', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q089', 'B', 'anger', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q089', 'C', 'panic', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q089', 'D', 'avoidance', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q090', 'A', 'quiet', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q090', 'B', 'chaotic', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q090', 'C', 'distracting', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q090', 'D', 'stressful', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q091', 'A', 'keep trying', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q091', 'B', 'give up', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q091', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q091', 'D', 'blame', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q092', 'A', 'clear', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q092', 'B', 'unclear', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q092', 'C', 'changing', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q092', 'D', 'none', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q093', 'A', 'modeling', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q093', 'B', 'criticizing', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q093', 'C', 'mocking', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q093', 'D', 'avoiding', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q094', 'A', 'relaxation', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q094', 'B', 'panic', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q094', 'C', 'avoidance', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q094', 'D', 'blaming', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q095', 'A', 'open', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q095', 'B', 'closed', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q095', 'C', 'stressful', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q095', 'D', 'avoidant', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q096', 'A', 'available', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q096', 'B', 'unavailable', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q096', 'C', 'dismissive', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q096', 'D', 'angry', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q097', 'A', 'complete', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q097', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q097', 'C', 'complain', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q097', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q098', 'A', 'breathing', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q098', 'B', 'shouting', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q098', 'C', 'blaming', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q098', 'D', 'avoiding', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q099', 'A', 'find', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q099', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q099', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q099', 'D', 'copy', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q100', 'A', 'recognizing', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q100', 'B', 'ignoring', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q100', 'C', 'criticizing', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q100', 'D', 'downplaying', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q101', 'A', 'feelings', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q101', 'B', 'nothing', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q101', 'C', 'random topics', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q101', 'D', 'avoidance', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q102', 'A', 'realistic', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q102', 'B', 'impossible', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q102', 'C', 'unclear', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q102', 'D', 'none', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q103', 'A', 'educational', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q103', 'B', 'stressful', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q103', 'C', 'confusing', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q103', 'D', 'none', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q104', 'A', 'celebrating', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q104', 'B', 'ignoring', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q104', 'C', 'criticizing', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q104', 'D', 'downplaying', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q105', 'A', 'complete', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q105', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q105', 'C', 'delay', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q105', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q106', 'A', 'relaxation', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q106', 'B', 'panic', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q106', 'C', 'avoidance', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q106', 'D', 'blaming', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q107', 'A', 'attempt', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q107', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q107', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q107', 'D', 'copy', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q108', 'A', 'listening to', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q108', 'B', 'ignoring', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q108', 'C', 'mocking', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q108', 'D', 'minimizing', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q109', 'A', 'calming skills', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q109', 'B', 'anger', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q109', 'C', 'panic', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q109', 'D', 'avoidance', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q110', 'A', 'distractions', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q110', 'B', 'support', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q110', 'C', 'structure', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q110', 'D', 'encouragement', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q111', 'A', 'try again', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q111', 'B', 'quit', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q111', 'C', 'avoid', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q111', 'D', 'blame', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q112', 'A', 'predictable', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q112', 'B', 'chaotic', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q112', 'C', 'rare', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q112', 'D', 'random', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q113', 'A', 'modeling', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q113', 'B', 'criticizing', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q113', 'C', 'mocking', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q113', 'D', 'avoiding', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q114', 'A', 'coping skills', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q114', 'B', 'panic', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q114', 'C', 'avoidance', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q114', 'D', 'blaming', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q115', 'A', 'open', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q115', 'B', 'closed', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q115', 'C', 'stressful', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q115', 'D', 'avoidant', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q116', 'A', 'encouragement', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q116', 'B', 'criticism', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q116', 'C', 'silence', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q116', 'D', 'avoidance', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q117', 'A', 'complete', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q117', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q117', 'C', 'delay', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q117', 'D', 'ignore', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q118', 'A', 'breathing', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q118', 'B', 'shouting', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q118', 'C', 'blaming', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q118', 'D', 'avoiding', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q119', 'A', 'make', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q119', 'B', 'avoid', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q119', 'C', 'fear', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q119', 'D', 'copy', 0::numeric, 4),
      ('SAFEPARENT_FILL_Q120', 'A', 'recognizing', 1::numeric, 1),
      ('SAFEPARENT_FILL_Q120', 'B', 'ignoring', 0::numeric, 2),
      ('SAFEPARENT_FILL_Q120', 'C', 'criticizing', 0::numeric, 3),
      ('SAFEPARENT_FILL_Q120', 'D', 'downplaying', 0::numeric, 4)
  ) as option(item_key, value, label, score, display_order)
)
insert into public.assessment_item_response_options (item_id, label, value, score, display_order)
select items.id, options.label, options.value, options.score, options.display_order
from items
join options on options.item_key = items.item_key
on conflict (item_id, value) do update
set
  label = excluded.label,
  score = excluded.score,
  display_order = excluded.display_order;
